### ISSUE TITLE
Mending Issues

### ISSUE THREAD

**Issue by rjwolfe3** [NillerMedDild/Enigmatica4#100]
**Modpack version**
v0.1.9

**Issue**
Not sure if this a bug or supposed to be like this. For some reason mending doesn't work on any gear or armor. I first noticed it when I made a mob farm that items were not repairing. I then tried mining coal with a stone pickaxe and one item with mending that need repaired. No change in durability. I went into creativity and pulled out a stack of xp bottles and used them all on one item and it did not repair. Is there a different way that mending works in this pack?

**Logs**
No log

**Comment by NielsPilgaard** [comment]
This is not intended, I'll look into it, thank you for the report :)

**Comment by NielsPilgaard** [comment]
I can't reproduce this, maybe a mod update fixed it :P
