### ISSUE TITLE
Unification (Ores/Ingot etc)

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica4#109]
Make a unification script, and a materials script.

**Comment by NielsPilgaard** [comment]
Waiting for help/explaination on CrT Discord - Not sure if this is possible atm, maybe I'll have to rethink how I do unification.

**Comment by TheUntamed** [comment]
why not use the instantUnify mod? Or is it not what you want to do?

**Comment by NielsPilgaard** [comment]
That's more of a bandaid than a fix imo, I think it appears a bit sloppy for items to change like that to be honest.
