### ISSUE TITLE
[Request] Add Glassential and Turf

### ISSUE THREAD

**Issue by Lykrast** [NillerMedDild/Enigmatica4#11]
[Glassential](https://www.curseforge.com/minecraft/mc-mods/glassential) and [Turf](https://www.curseforge.com/minecraft/mc-mods/turf) are two small mods that add building options.

While they don't really need any testing I'm sure some people will be happy to have those options available to build with.

**Comment by NielsPilgaard** [comment]
Nice suggestions, I'll most likely add them :)
