### ISSUE TITLE
Enigmatica 4 Issue

### ISSUE THREAD

**Issue by BrendanoElTaco** [NillerMedDild/Enigmatica4#110]
**Modpack version**
Enigmatica 4 v0.2.1
Using Forge-1.14.4-28.1.74

**Issue**
Crashes whenever I use a keyboard shortcut. EX: alt-tab, crtl-c

**Logs**
https://pastebin.com/VAE5epie
[crash-2019-11-03_20.03.39-client.txt](https://github.com/NillerMedDild/Enigmatica4/files/3802431/crash-2019-11-03_20.03.39-client.txt)

**Comment by NielsPilgaard** [comment]
Thanks for the report. Are you certain you're using 0.2.1? I fixed this already.

**Comment by NielsPilgaard** [comment]
So I see both the forge version and modpack version listed do not match the ones in your crash report. Please try updating before making an issue in the future, and at the very least don't lie about your versions.
