### ISSUE TITLE
Add Elrol's Server Utilities

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica4#112]
QoL commands! 

https://www.curseforge.com/minecraft/mc-mods/elrols-server-utilities

**Comment by NielsPilgaard** [comment]
Permissions need to be solid before adding this, make sure to test this.

**Comment by Halfdeaf** [comment]
An alternative if this one doesn't work out

https://www.curseforge.com/minecraft/mc-mods/maessentials

**Comment by NielsPilgaard** [comment]
Thanks! I think we'll go with this one :)

**Comment by Elrol** [comment]
With which one?
Lol

**Comment by NielsPilgaard** [comment]
Yours :P

**Comment by Elrol** [comment]
The latest version (v0.9.0) should be more stable then the others. Made a hot fix to fix one issue, and it led to another issue poping up that had to be fixed. Lol.

**Comment by NielsPilgaard** [comment]
Needs more testing after all.

**Comment by Elrol** [comment]
My apologies, with the addition of modded support for commands things got a bit funky, if you find any more issues, let me know, and I will have them fixed asap. I am currently having one guy try to break it to see what other aspects of the mod have bugs.

**Comment by NielsPilgaard** [comment]
No problem, thanks for added info!

**Comment by Elrol** [comment]
Just pushed a build that adds kits and fixes a few bugs. its version 0.9.4

**Comment by NielsPilgaard** [comment]
It needs more work. I'll revisit it in a few weeks, I think.
