### ISSUE TITLE
Add Quark

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica4#115]

**Comment by Halfdeaf** [comment]
Quark is incompatable with Toast Control at the moment due to this issue in Forge https://github.com/MinecraftForge/AccessTransformers/issues/8#issuecomment-550434425

**Comment by NielsPilgaard** [comment]
Thanks for letting me know :D

**Comment by Halfdeaf** [comment]
Wow that was fast. Already fixed :) https://github.com/MinecraftForge/AccessTransformers/commit/94458e7e53589931dc7849f86b3098463038a0f7

**Comment by NielsPilgaard** [comment]
Configs are done, worldgen needs to be evaluated next, and then comes playtesting - But playtesting will be done with update 0.2.2.
