### ISSUE TITLE
mysticallib crash

### ISSUE THREAD

**Issue by Halfdeaf** [NillerMedDild/Enigmatica4#117]
Reported to MysticMods

https://github.com/MysticMods/MysticalLib/issues/31

**Comment by NielsPilgaard** [comment]
Thanks for the report :D

**Comment by noobanidus** [comment]
I believe Niller has actually reported this already, I just haven't really had the time to put out a new build and it didn't seem urgent enough to warrant a single release. I aim to have replacement builds out by this weekend.

**Comment by NielsPilgaard** [comment]
Would you say that you have fixed this issue @duely? :)

**Comment by noobanidus** [comment]
I ... think so? I've definitely done a release since I said that, so I'm pretty sure it's done.

**Comment by NielsPilgaard** [comment]
Cool :D

**Comment by noobanidus** [comment]
There's a new release out so at the very least it's fixed in that
