### ISSUE TITLE
Biome tweaking

### ISSUE THREAD

**Issue by Halfdeaf** [NillerMedDild/Enigmatica4#147]
The conclusion of my world gen/biome investigation. There are definitely some areas to improve on. Some biomes generate far too often and others not enough. Vanilla biomes are very scarce and from my roughly 5000x5000 trip around the server world, the modded biomes are overtaking most of the vanilla biome spots. 

BpP has a tp to biome command that works for biome namespace and as far I can tell there is for example not a single Bamboo Jungle on the server. I successfully located biomes and far out as 7000 blocks with that command so according to my testing, there is definitely no Bamboo Forest within about 12k blocks from spawn. If I load the same seed into Amidst in vanilla I can find it in at least 3 different spots within 5k blocks from spawn. Mini Jungle from traverse is also a jungle variant like Bamboo Jungle and I suspect it's overriding it every time as I found a good number on the server. 

The good news is that I spoke to Nooby on the Mystic Mods discord and he has a plan to implement configs to tweak the frequency off biomes and turn them off if we so choose. I saw some mention of configs being planned for BoP and I'm waiting for an answer as to what is planned with them. I also left a suggestion for Voyage 

https://github.com/Lykrast/Voyage/issues/5

**Comment by NielsPilgaard** [comment]
Great work!

**Comment by NielsPilgaard** [comment]
Traverse is now configurable, as of v2.0.3: https://www.curseforge.com/minecraft/mc-mods/traverse-legacy-continued/files/2838890

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/traverse-legacy-continued/files/2838890">Attention Required! | Cloudflare</a></strong></div></blockquote>

**Comment by Halfdeaf** [comment]
Update: BoP will most likely not receive any more updates on 1.14 so no dice there on getting configs to tweak. Lykrast is looking into it with Voyage
