### ISSUE TITLE
Add Tetra

### ISSUE THREAD

**Issue by Halfdeaf** [NillerMedDild/Enigmatica4#150]
https://www.curseforge.com/minecraft/mc-mods/tetra

**Comment by NielsPilgaard** [comment]
1. Craft a mallet using two sticks and two logs
    2. Craft and place a vanilla crafting table
    3. Right click the table with the mallet to upgrade it into a workbench
    4. Craft a vanilla weapon or a tool and place it in the workbench
    Check the advancements window for hints on how to progress further
