### ISSUE TITLE
Nerf Refined Storage Addons

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica4#154]
Subtask of #153 
The energy usage and probably recipe will need tweaking.

**Comment by geoffmca** [comment]
Should you also update refinedstorage-server.toml 

[wirelessGrid]
[wirelessFluidGrid]
[portableGrid]
[wirelessCraftingMonitor]

Unsure about this but mentioning it. 
[controller]
capacity?

**Comment by NielsPilgaard** [comment]
Yeah probably, thanks for the reminder :)
