### ISSUE TITLE
[Feedback] Nether Fortress loot

### ISSUE THREAD

**Issue by Discomanco** [NillerMedDild/Enigmatica4#160]
**Modpack version**
0.2.3

Did some Nether Fortress loot testing, and it's a bit.. rubbish.
A test from 30 chests (`/setblock ~ ~ ~ minecraft:chest{LootTable:"minecraft:chests/nether_bridge"}`)
![image](https://user-images.githubusercontent.com/4707702/69457445-5c56a500-0d6d-11ea-9bff-3b9a2f7236be.png)  
plus 11 Ability Totems (which seems fine in terms of totem quality). A lot of chests only contained Quark Runes, and nothing else.
Made test after running through my first nether fortress, thinking it was partially looted already.

**What could be added?**
There's plenty of baubles and other fun toys, maybe even other golden tools, food, potions?, some rarer Apotheosis enchanted books of low lvl and random Ensorcellation books

**Comment by NielsPilgaard** [comment]
Damn, that is weak :P we'll definitely change that!
