### ISSUE TITLE
Investigate Quark stone type generation

### ISSUE THREAD

**Issue by Halfdeaf** [NillerMedDild/Enigmatica4#161]
Quark limits stone variants to specific biomes. Some quick testing suggests they might be too rare. I tested modded biome variants on andesite which is set to spawn only in forests and it seems to spawn in those too. However, I don't see enough pockets given that you only find it in those biomes. I'll test some more and come up with some values that make sense

**Comment by NielsPilgaard** [comment]
This looks good to me atm, I'll make recipes for the various stones #245
