### ISSUE TITLE
Items with NBT act badly inside the vanilla crafting table

### ISSUE THREAD

**Issue by Darkere** [NillerMedDild/Enigmatica4#169]
**Modpack version**
0.2.3

**Issue**
Inserting 3 Everlasting Abilities totems into the crafting table allows you to extract the result multiple times.
https://gfycat.com/FlamboyantLikableBronco

Any item with NBT that is moved around inside the crafting table has a chance to get voided.
https://gfycat.com/AnguishedDelightfulBeetle

Both get fixed by removing Crafttweaker, Crafttweaker alone doesn't produce the problem though. So probably something in the scripts that causes it.

**Comment by NielsPilgaard** [comment]
Yikes, that doesn't sound good. The scripts we have at the moment are fairly standard, so that could mean a deeper CraftTweaker issue, or I'm failing at the new syntax in some hidden way :P

**Comment by Darkere** [comment]
Could theoretically also be another mod interfering somehow. Although I don't know which one that would be. Tested with just FastWorkbench and crafttweaker too.

**Comment by NielsPilgaard** [comment]
Alright, I'll keep this in mind when bug hunting, thanks for the report!

**Comment by NielsPilgaard** [comment]
Any update on this? Does it still exist?

**Comment by Darkere** [comment]
Haven't had any issues since the Crafttweaker fix a couple versions back. Gonna Call it fixed for now.
