### ISSUE TITLE
Platinum Ore can now be veinmined

### ISSUE THREAD

**Issue by SummitSummit** [NillerMedDild/Enigmatica4#171]
**Modpack version**
0.3.1

**Issue**
Platinum ore from Silent's Mechanism needs to be added to the Ore Excavator whitelist. 

**Logs**
N/A

**Comment by NielsPilgaard** [comment]
I'll get that fixed one way or the other, ty :)
Reported to mod author here:
https://github.com/SilentChaos512/Silents-Mechanisms/issues/52

**Comment by NielsPilgaard** [comment]
I just did it myself, will be in the next update.
