### ISSUE TITLE
Tetra Holosphere breaks crafting when used.

### ISSUE THREAD

**Issue by scarfkitten** [NillerMedDild/Enigmatica4#174]
**Modpack version**
0.3.1

**Issue**
Occurs as soon as the player crafts the Tetra hammer and utilizes the Holosphere.
Seems to be very arbitrary; it happened as soon as I got the Tetra hammer and opened the sphere in my survival world, but in the linked log below it took some time to occur.
Completely breaks crafting as a whole, even vanilla recipes. 
Persists through world changes, stops on a full restart. 

note: managed to post this to e2ex repository somehow the first time. big sorries!

**Logs**
Starts at line 6368.
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/3919406/latest.log)
![image](https://user-images.githubusercontent.com/32282644/70102885-80d13d80-1607-11ea-85ad-584e84ec0e3d.png)

**Comment by NielsPilgaard** [comment]
Np :P 
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
@Mickelus, I hope you don't mind the ping - Would you mind seeing if you can replicate this, if you already have a Tetra-only dev instance? :)

**Comment by NielsPilgaard** [comment]
I cannot reproduce this.
Edit: Was it on a server?

**Comment by Darkere** [comment]
It did not happen on a server either. Although we have also experienced the broken recipes. Still investigating what might be the cause.

**Comment by scarfkitten** [comment]
This was on a singleplayer world.

I did unintentionally leave out a vital detail: I'm using Optifine. There's a chance that this is related to Optifine? Seems weird but I know OF changes a LOT of stuff so.

quick edit: using a vanilla crafting table

E2: thanks for the heads up about my java version! twitch launcher can be such a pain...

**Comment by NielsPilgaard** [comment]
Ah this issue should actually have been fixed yesterday in CraftTweaker - Halfdeaf reported an issue on their Discord yesterday, and they released a new version today.

Also, your java is set to the Twitch default version, which does not run very well - I recommend you get that sorted :)

**Comment by mickelus** [comment]
No worries!
In the provided log the crash appears to happen from within crafttweaker. I set up an instance with just tetra and craftweaker and I'm unable to reproduce it there, but I can reproduce it with the modpack using the following steps:
1. Open holosphere
2. Click toolbelt
3. Click one of the "slot" slots (sword->fuller and tool->binding also works)
4. Close holosphere
5. Open a crafting table (or anything that supports shaped crafting)
6. Attempt to craft a shaped recipe

I don't know why this is happening yet, but I do know that:
- This happens after you view schemas for a slot that's not required (e.g. players can remove modules from that slot)
- The crash happens on the "server" side when crafttweaker is comparing NBT tags

**Comment by mickelus** [comment]
Oh, they fixed it in crafttweaker?
I'm so confused, I don't understand how this could even happen to begin with :D
