### ISSUE TITLE
Tetra Configuration

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica4#175]
This is the master issue for tracking, planning and PR'ing Tetra configurations.
Input, feedback and suggestions are welcome.

**Comment by mickelus** [comment]
I've looked around a bit, so far I've found

Handles/hilts:
- [ ] bamboo
 - [ ] fir
 - [ ] redwood
 - [ ] cherry (already available, needs tag entry)
 - [ ] mahogany
 - [ ] jacaranda
 - [ ] palm
 - [ ] willow
 - [ ] magic wood
 - [ ] umbran
 - [ ] hellbark
 - [ ] ethreal wood

tool heads/blades:
- [ ] amethyst
- [ ] sapphire
- [ ] malachite
- [ ] ruby
- [ ] platinum
- [ ] bismuth steel (sounds cool but irl bismuth alloys appear to be weak?) 

wrapping/binding/toolbelt modules:
- [ ] silk thread 
- [ ] pelt
- [ ] dusk lurker fur
- [ ] vrontausaurus fur

Would also be interesting to do something with:
- [ ] andesite alloy
- [ ] blaze brass
- [ ] chorus chrome

Not sure about what's easy to obtain of this, so we'll need to play around a bit in the pack to figure out some progression curves. It could be interesting to do some situational stuff with some of them, like having ethreal wood providing a durability multiplier but 0 flat durability while not requiring repairs. And magic wood could have very high enchantability at the cost of something else.

I'm guessing we could move the stuff you'd like to have in the pack from this comment (and future comments) to the main issue, to make it easier to keep track off?

**Comment by NielsPilgaard** [comment]
Are all those materials ones that you propose compatibility for, or that could/should be tweaked?

**Comment by mickelus** [comment]
I'm proposing compatability ^^

**Comment by NielsPilgaard** [comment]
All good ideas :D if you show me the data pack syntax for Tetra I'll gladly get started.

**Comment by NielsPilgaard** [comment]
By the way, are you planning JEI integration? I'm sure Tetra would be used a ton more if it had JEI integration.

Also, the workbench is unlocalized in English.

**Comment by mickelus** [comment]
Sorry for being slow, I've been reworking how module models work and I didn't want to do a PR with the new format before I knew it was going to work.

I agree that JEI integration could increase affordance, there's some stuff I want to get in before I start working on the flows and layouts for that though. If you got some suggestions I'm all ears.

**Comment by NielsPilgaard** [comment]
No worries at all, quality over speed! 
I'll let you know if I come up with something cool.

**Comment by NielsPilgaard** [comment]
I've moved lang stuff to `kubejs\assets\enigmatica\lang` because I was having trouble getting the other location to work.

**Comment by mickelus** [comment]
Apologies for the silence, I'm reworking how item modules are textured and how the data setup works.

The data setup will make configuration overrides easier to maintain (i.e. a copy of the default setup does not have to the present in the tetra datapack in e4).

The module textures rework will make it so that it's no longer neccessary to maintain unique textures for all module variants (i.e. iron basic blade, oak basic blade, cobblestone basic blade etc), it's enough to provide a tint color and the base texture is tinted at "bake time".

I'm guessing I'm about a week away from having both of those finished.

**Comment by NielsPilgaard** [comment]
Both of those changes sound great :D Looking forward to them!

**Comment by NielsPilgaard** [comment]
Would you mind checking if I've reconfigured the datapack correctly? :)

**Comment by mickelus** [comment]
The sword module file also had to contain a json object on the root level. I've got a PR coming up with a fix along with a bunch of content

**Comment by NielsPilgaard** [comment]
I know it's an odd place to ask, and an annoying question for most mod authors, but where's your stance on moving to 1.15.2? :)

**Comment by mickelus** [comment]
I thought 1.15 was still a bit shaky so I've barely looked into it. Are you looking into completely moving over to enigmatica 5?

**Comment by NielsPilgaard** [comment]
Yep I am, it looks pretty much as stable as 1.14.4 :)

I think it's fairly easy to port from 1.14 to 1.15, with the exception of rendering changes. I believe McJty has made a guide for it.

**Comment by Mechrior** [comment]
I know it has probably been asked but how are we to progress if the ruins NEVER contain the machinery we need to upgrade things like the hammer?

**Comment by ghost** [comment]
This issue was moved by [NillerMedDild](https://github.com/NillerMedDild) to [NillerMedDild/enigmatica5#158](https://github.com/NillerMedDild/enigmatica5/issues/158).

**Comment by NielsPilgaard** [comment]
This will be revisited in E5, closing for now :)
