### ISSUE TITLE
Watering Can doesn't water while looking at crops.

### ISSUE THREAD

**Issue by rockdemon696** [NillerMedDild/Enigmatica4#181]
**Modpack version**
0.3.1

**Issue**
Watering Can doesn't water while looking at crops. There is not much else to say here. It seems to be a conflict with right click harvest but that is just a guess.

**Comment by NielsPilgaard** [comment]
Does it work if you hold shift?

**Comment by rockdemon696** [comment]
Nope, just fired up my world to double check and I got nothing unless I was looking at bare ground regardless of whether shift was pressed or not.

**Comment by rockdemon696** [comment]
I also loaded up a world with just watercan and it does work there so it's definitely a conflict of some kind.

**Comment by NielsPilgaard** [comment]
Thanks, I'll see what I can do :)

**Comment by NielsPilgaard** [comment]
I made an issue for it here: https://github.com/codetaylor/watercan/issues/16

**Comment by NielsPilgaard** [comment]
It was not possible from watercan's side, trying Simple Farming! https://github.com/enemeez/simplefarming/issues/47
