### ISSUE TITLE
Add KubeJS

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica4#182]
It looks pretty damn good to be honest. At the moment we can use it for creating items and checking configs to enable/disable specific behaviour. (AE2 channels for example)

Not sure how much is ported to 1.14.4 though

**Comment by Halfdeaf** [comment]
> Aurora integration
> player.addXP
> and block hardness/other property overrides

Still missing from the 1.14 version, quoted from a Lat on his discord

**Comment by NielsPilgaard** [comment]
That's all? We can make blocks?!

**Comment by Halfdeaf** [comment]
Most everything is in yes. Aurora is the actual documentation but we can access that for 1.12. Some things have changed between versions. Making new blocks specifically is possible

**Comment by NielsPilgaard** [comment]
Sweeeeet! Guess I have to get better at JS
