### ISSUE TITLE
Investigate GrassWorld

### ISSUE THREAD

**Issue by Halfdeaf** [NillerMedDild/Enigmatica4#183]
This latest update added a bunch of new functionality, not just decorative anymore.  
https://www.curseforge.com/minecraft/mc-mods/grassworld

**Comment by NielsPilgaard** [comment]
I don't know :/

**Comment by Halfdeaf** [comment]
I'm going to block this for now. It's neat and might have a place if we do some creative things with a skyblock mode.

**Comment by NielsPilgaard** [comment]
I'm actually gonna close this, it clutters my brain for some reason :P
