### ISSUE TITLE
Vanilla chest recipe conflicting with Quark (All wooden chests can now be crafted in the vanilla chest)

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica4#188]
**Modpack version**
0.3.2

**Issue**
Title says it all. Only way to get the vanilla chests is by using the treated crafting table. Otherwise both 8 oak logs or 8 oak planks give you quark chests. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by scarfkitten** [comment]
JSYK: you can use Biomes Oplenty wood to make standard vanilla chests, like so. For this particular wood you can find it in swamps iirc, but any bop wood should work.
https://i.imgur.com/Z98euVS.png

<blockquote></blockquote>

**Comment by NielsPilgaard** [comment]
Why do you need a vanilla chest? :)

**Comment by jinkhya** [comment]
For minecolonies structures :)

**Comment by NielsPilgaard** [comment]
Ahh alright.

**Comment by jinkhya** [comment]
actually since they're not oredicted you can't use quark chests for recipes either, like drawers for example :)

**Comment by NielsPilgaard** [comment]
They are oredicted and can be used for a ton of recipes.
