### ISSUE TITLE
Dimensional Shard Ore and Nether Dimensional Shard Ore cannot be vein mined.

### ISSUE THREAD

**Issue by scarfkitten** [NillerMedDild/Enigmatica4#189]
**Modpack version**
0.3.2

**Issue**
Doesn't matter so much for the normal ore, as it usually only spawns as a single block in any given vein and is quite rare to boot, but the bottom of the nether is COVERED in it.

**Logs**
n/a

**Comment by NielsPilgaard** [comment]
Thanks for the report, I'll get that fixed :)
