### ISSUE TITLE
Crash KubeJS

### ISSUE THREAD

**Issue by Darkere** [NillerMedDild/Enigmatica4#190]
**Modpack version**
0.3.2

**Issue**
Crash. Not sure if your code or KubeJS. 

**Logs**
https://hatebin.com/lniezejcqm

**Comment by NielsPilgaard** [comment]
I made no KubeJS stuff, so it's definitely KubeJS - what were you doing when it happened?

**Comment by Darkere** [comment]
Nothing specifically. I was just near another player.

**Comment by Darkere** [comment]
Gonna report to them then.

**Comment by NielsPilgaard** [comment]
Thanks a lot! Linking the issues.
https://github.com/KubeJS-Mods/KubeJS/issues/6
