### ISSUE TITLE
Basalt Inconsistencies

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica4#193]
Does Basalt from Quark spawn? Should it?
Recipe to convert between Basalt types perhaps.

**Comment by Halfdeaf** [comment]
Quark basalt only spawns in the nether, I like the idea of having different types of basalt so my vote is for conversion recipes

**Comment by NielsPilgaard** [comment]
Blue Power Basalt can now be crafted into Quark Basalt, and the other way around.
