### ISSUE TITLE
Mobs aren't spawning on vector plates.

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica4#195]
**Modpack version**
0.3.4

**Issue**
Hello !
I tried making a mobfarm which doesn't work at the moment. Here's an example on a creative testing world : https://i.imgur.com/IafL1Ax.png 
Mobs are spawning everywhere except on vectors. If I remove the vectors they spawn just fine.

I believe it should still work in 1.14, the description for them specifies they can spawn on and in them : https://i.imgur.com/tBNqHFU.png
Thanks :)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thanks for the report, I'll relay it :)
Can I have a screenshot of inside the mobfarm, with light on?

**Comment by jinkhya** [comment]
Here, I made a better screenshot with night vision on.
This is with same versions of Enigmatica but without the other mods to confirm it's the mod itself and not a conflict with something else. So forge 103, Bookshelf 4.4.71 and dark utilities 2.0.8.

https://i.imgur.com/FGmHiwm.png

<blockquote></blockquote>

**Comment by NielsPilgaard** [comment]
Great work, thank you :D
