### ISSUE TITLE
Blue power ores drop xp with silk touch tools

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica4#196]
**Modpack version**
0.3.4

**Issue**
Mining Blue power ores that normally drop gems (teslatite, ruby, sapphire, malachite, amethyst ]with a vanilla pickaxe with silk touch or the mining gadget with silk touch drops xp allowing you to place / break indefinitely to farm xp.

**Comment by NielsPilgaard** [comment]
Reported here https://github.com/Qmunity/BluePower/issues/528
Thanks for the report!
