### ISSUE TITLE
Upgrading drawers requires opening the GUI

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica4#197]
**Modpack version**
0.3.4

**Issue**
I don't know if this is intended / changed in 1.14 but currently to upgrade drawers you have to shift right click them to open the GUI to insert the upgrades instead of just right clicking them with the upgrade in hand.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Reported here: https://github.com/jaquadro/StorageDrawers/issues/780
Thanks for yet another report :D I think this is a bug, but we'll see.
