### ISSUE TITLE
Drying rack randomly crashing my client when I teleport back home.

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica4#198]
**Modpack version**
0.3.4

**Issue**
Twice today my client has crashed when I do /mc home. It's not consistent.
From crash-report it looks like it's the drying racks rendering causing it.

**Logs**
https://hastebin.com/xamuxeniko.pl

**Comment by jinkhya** [comment]
That being said it could be an optifine issue actually. (it does appear as well in the crash-log)

**Comment by NielsPilgaard** [comment]
Yup looks like Optifine :)
