### ISSUE TITLE
Everlasting Abilities: Thoughts

### ISSUE THREAD

**Issue by Discomanco** [NillerMedDild/Enigmatica4#199]
Mod is super powerful, when the passive hunger is disabled (and super annoying when enabled), and there are outliers that are simply too powerful and make you close to invincible early game. Some abilities should be removed, a few of them rarer.

* Haste  
At this stage, it should be rarer. Haste II+ and you invalidate the potential use of beacons (Not much else use for Nether Stars atm), max level of 1 or 2
* Regeneration  
Very strong, either needs removal or very rare. Max level of 1
* Resistance  
Outright remove, there is no doubt the power of Resistance is too high. Resist I could be debated as super-rare, but currently with Resist II, I don't take damage, except for 1½ heart from hugging a Creeper.
* Saturation  
Remove, removes all need for eating
* Water Breathing
While it's currently single-level and very common, it still quite a nice ability, not having to worry about breath. May need some tweaking
* Absorbtion  
Quite strong, but it's not a permanent absorb. Applies 4 health of absorb for 5 seconds every 20 second or so.

A lot (or all) of the combat ones are probably fine, as they apply debuffs around you in an aura, like Poison, Power Stare, Weakness, Slowness.

The Utility ones are quite nice (Water Breathing belonging here) and are ones I really like from it. Step Assist, Jump Boost, Speed

**Comment by jinkhya** [comment]
I agree with Disco. I'll add :
- Fire resistance is a bit strong. Blazes don't do any damage to you with their projectiles, and you can swim in lava peacefully which makes the nether a bit dull ^^
- Strength gets quite strong too with tiers. you might need to max it at 1 or 2 and/or make it rarer.  
My fav might be speed (although to be honest speed 5 is a bit ridiculous and if you explore new chunks in a dimension that is not pregened on a server it gets quite heavy on the ticks), step assist, water breathing and night vision.

**Comment by jinkhya** [comment]
Oh forgot to add a suggestion, totems could only drops from hostiles (or even some hostiles). Getting saturation from a rabbit is quite a reward :P

**Comment by NielsPilgaard** [comment]
Thanks a ton for the feedback guys, I've made changes according to your findings:
```
- Everlasting Abilities: Reduced the max rarity of the totem you spawn with from 3 to 2.
- Everlasting Abilities: Neutral mobs (pigs, cows...) can no longer drop totems.
- Everlasting Abilities: Reduced the max level of the Haste ability from 5 to 2.
- Everlasting Abilities: Reduced the max level of the Regeneration ability from 3 to 1.
- Everlasting Abilities: Increased the rarity of the Regeneration ability from 2 to 3.
- Everlasting Abilities: Increased the rarity of the Fire Resistance ability from 1 to 2.
- Everlasting Abilities: Increased the xp needed to get Fire Resistance from 20 to 30 levels.
- Everlasting Abilities: Removed the Saturation ability, as it allows you to skip food completely.
- Everlasting Abilities: Removed the Resistance ability, as it makes you immortal on level 2 and above.
- Everlasting Abilities: Increased rarity and xp requirement of Waterbreathing (from 0 to 1, and from 10 to 15)
- Everlasting Abilities: Increased rarity and xp requirement of Strength (from 1 to 2, and from 20 to 35)
- Everlasting Abilities: Decreased the max level of Strength from 5 to 3
```
