### ISSUE TITLE
Rftools Matter transmitter/receiver issues when set to "Private"

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica4#200]
**Modpack version**
0.3.4

**Issue**
Hello,
Unless I'm missing something I think the Matter transmitters and receivers are not fully working properly :
- When you set the transmitter to "private" and add your mc name to the list to allow yourself, you can no longer teleport anywhere.
- When you set the receiver to "private" and add your mc name to the list, you cannot see it in the list in the dialer anymore. (The way around this one is to leave it public, dial, and then set it to private. However if you want to interrupt the dial, you wouldn't be able to dial on it again, unless you set it back to public before doing so). I feel like this is not clear lol... Let me know if this is confusing. I'll make a video or something.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Would you mind reporting this issue to [this issue tracker](https://github.com/McJtyMods/RFToolsUtility/issues) please? I'd have trouble answering questions about the setup they may have :)

**Comment by jinkhya** [comment]
no problem I'll post there :)

**Comment by jinkhya** [comment]
Here it is : https://github.com/McJtyMods/RFToolsUtility/issues/13

**Comment by NielsPilgaard** [comment]
This will most likely not be solved, as the mod is no longer received updates on 1.14.4 as far as I know.
