### ISSUE TITLE
[Suggestion] Add the Dragon scale (quark) as a second option to disable checking conditions on Apotheosis spawners

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica4#201]
**Modpack version**
0.3.4

**Issue**
Since the dragon only drops its egg the first time it's killed, it makes it impossible for other players on a server to use that modifier. The dragon drops 1 dragon scale from quark when killed (the first time killed it won't, it will only drop the egg). I saw on Apotheosis' page CT can be used to customize the modifiers. I'm not sure you can have multiple items for one type of modifier though.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
I'll try :D good idea.

**Comment by NielsPilgaard** [comment]
It looks like you can't have more than 1 item per modifier I'm afraid, but it would make sense to change it to Dragon Scales

**Comment by jinkhya** [comment]
The first player killing the dragon will have to kill it another time to get the scale as well (or ask Vazkii to add a config to always drop the scale when the dragon is killed :P ) 

Actually another solution would be to modify the loottable so the dragon always drops the said item you need as modifier.
