### ISSUE TITLE
Mining Gadgets bypass the protection in dimensional dungeons

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica4#202]
**Modpack version**
0.3.4

**Issue**
Vanilla tools can't break blocks in there so you can't "cheese" the dungeon. However the mining gadget can break any block in that dimension.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thanks for the report, I relayed it here: https://github.com/Direwolf20-MC/MiningGadgets/issues/41
