### ISSUE TITLE
Add Serene Seasons

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica4#203]
https://www.curseforge.com/minecraft/mc-mods/serene-seasons

**Comment by NielsPilgaard** [comment]
I really like it, but I'm afraid the majority would not.
Re-evaluate once Simple Farming crops have seasonal values in there.

**Comment by axieum** [comment]
Came here to recommend this mod, our server is currently running it. But as you mentioned, we need manually add the Simple Farming seeds and their seasons to the config file.

Another issue I noticed while running the mod for a bit, is that the Botany Pots allow you to bypass the seasons (can grow any seed at any time) - Darkhax-Minecraft/BotanyPots#7.

May also need to consider the Simple Farming berry bushes, and fruit trees - am yet to test or know if this would be possible to configure or if the mod itself needs to add optional support for Serene Seasons. I do believe these bushes and fruit trees were generating fruit during Winter.

**Comment by NielsPilgaard** [comment]
Sounds like someone *(probably me)* needs to request compatibility from Simple Farming for Serene Seasons to be really cool in E4. 
Edit: I appreciate the feedback btw, helps with the evaluation.

**Comment by Frikkle** [comment]
I would love this too, though I'm not your regular player :)
