### ISSUE TITLE
Breaking Xnet connectors (of any color) drops routing connectors

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica4#207]
**Modpack version**
0.3.4

**Issue**
Title says it all, it's already reported here : https://github.com/McJtyMods/XNet/issues/370
So it's more of a "for info" :)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
I know, I reported the issue :P https://github.com/McJtyMods/XNet/issues/364
Thanks anyway!

**Comment by jinkhya** [comment]
Lmao next time I'll read the name of who reported the issue sorry...

**Comment by NielsPilgaard** [comment]
no problem - The one you linked was by someone else, but I reported it the day before.
