### ISSUE TITLE
Fluidtanks issues

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica4#208]
**Modpack version**
0.3.4

**Issue**
- I think you're aware of the upgrade for fluid tanks working but not showing the right recipe in JEI ?
- The modded tanks (aka tin, copper etc) show recipes in JEI but the crafting action doesn't work. Like for example 4 wooden tanks with no other materials is supposed to give you 1 tin tank but when you click on it to craft it, it doesn't give you anything, ingredients go back to their slots in the crafting table.

It's overall a bit glitchy :)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Yep that does suck, to be honest I'm just waiting for any other fluid tank implementation and then I'll remove Large Fluid Tanks.

**Comment by jinkhya** [comment]
This update actually fixed all those issues \o/
Recipes are showing properly and working, including the recipes with modded ingots (whether or not they are from mystical world or silent's mechanism)

**Comment by NielsPilgaard** [comment]
Oh, awesome xD

**Comment by jinkhya** [comment]
It's broken again :( 
almost same thing as my initial post. JEI recipes are broken (like a stone tank only showing you need 4 wooden tanks, but not the stone as well) However you can still craft the tanks with modded ingots (when before ingredients were returning to their slots and not crafting anything)

**Comment by NielsPilgaard** [comment]
That's strange, I didn't update it in 0.3.6

**Comment by Cheata** [comment]
Just thought i should note that I'm having this issue in 0.4.4 tanks show up but the recipes don't work and jei shows them as just the 4 tanks in the corners with no center block. wooden tank builds fine.
