### ISSUE TITLE
Something happened to gears, they disappeared

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica4#209]
**Modpack version**
0.3.5

**Issue**
Can't craft any of the industrial foregoing machines, the gold gears don't exist anymore. 
https://i.imgur.com/VjFydav.png

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by jinkhya** [comment]
edit all gears are gone (diamond, iron as well)

**Comment by Darkere** [comment]
Dev released a Hotfix a day after we updated. That was probably addressed there.

**Comment by jinkhya** [comment]
ah ok they probably realised or it was reported in discord. I didn't see anything about it in their github. Glad to see it's fixed already :)

**Comment by NielsPilgaard** [comment]
I'll update asap :)
