### ISSUE TITLE
Feral lantern and Dread lamp  don't drop when you break them

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica4#210]
**Modpack version**
0.3.5

**Issue**
Feral lanterns and Dread lamps from torchmaster don't drop when you break them. The Mega torches from that same mod is the only one that drops fine when you break it. 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thanks for the report, I relayed it here: https://github.com/Xalcon/TorchMaster/issues/110
