### ISSUE TITLE
Xnet facades aren't working properly

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica4#211]
**Modpack version**
0.3.5

**Issue**
Xnet facades aren't usable. 
- You can't place them on cables.
- when you right click them on the floor it places a routing network cable : https://i.imgur.com/mwGgSBd.png
Breaking it the first time transforms the cable in the world into blue network Cable : https://i.imgur.com/vfwFdAK.png
Breaking it a second time gives you the blue network cable in your inventory https://i.imgur.com/MKDdnV4.png

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
From the latest XNet changelog: `- The facade block works much better now`
Updating to that, in version 0.3.6, please let me know if it resolves the issues :)
