### ISSUE TITLE
Facades on network cables break the connection 

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica4#213]
https://github.com/McJtyMods/XNet/issues/383

For info:)
Thought I should start reporting directly and linking here instead of giving you the work of relaying it ^^

**Comment by NielsPilgaard** [comment]
Awesome, thank you <3

**Comment by NielsPilgaard** [comment]
This will most likely not be solved, as the mod is no longer received updates on 1.14.4 as far as I know.

**Comment by kyleedwardsny** [comment]
Just ran into this myself. It looks like the mod has received a [fix](https://github.com/McJtyMods/XNet/commit/070abf7f1e87695c7914f401f024d081c37b4dc0) for 1.15. Would it at least be possible for you to backport the fix to Enigmatica?

**Comment by NielsPilgaard** [comment]
No, that's not up to me, I can't just change mods. Besides, If I started backporting bug fixes I would never be done :)
