### ISSUE TITLE
Screen renders what's behind the block on which it's attached to when set to transparent 

### ISSUE THREAD

**Issue by jinkhya** [NillerMedDild/Enigmatica4#214]
https://github.com/McJtyMods/RFToolsUtility/issues/15

**Comment by NielsPilgaard** [comment]
This will most likely not be solved, as the mod is no longer received updates on 1.14.4 as far as I know.

**Comment by NillerMedDild** [comment]
This will most likely not be solved, as the mod is no longer received updates on 1.14.4 as far as I know.
