### ISSUE TITLE
Tetra Hammer crash

### ISSUE THREAD

**Issue by josemoncab** [NillerMedDild/Enigmatica4#227]
**Modpack version**
Enigmatica 4 - 0.3.7

**Issue**
Tetra´s hammer crash if i open my inventory and hammer is in it.

**Logs**
https://pastebin.com/gGDTbw2f

**Comment by NielsPilgaard** [comment]
Why did you close the issue? :)

**Comment by josemoncab** [comment]
I close this because i try to replicate obtaining tetra`s hammer in my inv and cant replicate

**Comment by NielsPilgaard** [comment]
I see, thanks!

**Comment by josemoncab** [comment]
I do a video trying to reproduce and crash but not qhen i have tetra`s hammer in my inv, it crash when i interact with fastworkbench in this try

**Comment by NielsPilgaard** [comment]
And you're certain it's on `0.3.7`, not `0.4.0`?

**Comment by josemoncab** [comment]
yea, in 0.4.0 my bad

**Comment by josemoncab** [comment]
https://youtu.be/ORa6u38sioU

<blockquote><img src="https://i.ytimg.com/vi/ORa6u38sioU/maxresdefault.jpg" width="48" align="right"><div><img src="/yts/img/favicon_144-vfliLAfaB.png" height="14"> YouTube</div><div><strong><a href="https://www.youtube.com/watch?v=ORa6u38sioU">Crash</a></strong></div><div> </div></blockquote>

i click the hammer to move and crash

**Comment by NielsPilgaard** [comment]
Ah if it's 0.4.0 then it should be resolved in the next update. A bunch of stuff is broken there ^^

**Comment by josemoncab** [comment]
Aaah ok, thanks
