### ISSUE TITLE
Industrial Foregoing pulling from a side

### ISSUE THREAD

**Issue by AaronBoi** [NillerMedDild/Enigmatica4#229]
**Modpack version**
0.4

**Issue**
I placed down a latex processing unit (I don't know how it works for other machines) and had to reset every side in the IO window manually. When the "pull" was on a specific side, the game crashed and it crashes every time I'm in the world now.

**Logs**
The game crashed whilst ticking block entity
Error: java.lang.RuntimeException: Slot 0 not in valid range - [0,0)

**Comment by NielsPilgaard** [comment]
Please supply the crash report :)

**Comment by AaronBoi** [comment]
Here is the crash report:
https://pastebin.com/1Pbq1sgE

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/1Pbq1sgE">latex_processing_unit crash report - Pastebin.com</a></strong></div></blockquote>

**Comment by NielsPilgaard** [comment]
Thanks! While I don't think this it's the issue, your Java is outdated, FYI.

**Comment by NielsPilgaard** [comment]
The issue has been reported here: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/640

**Comment by NielsPilgaard** [comment]
This will most likely not be solved, as the mod is no longer received updates on 1.14.4 as far as I know.
