### ISSUE TITLE
Some mod suggestions

### ISSUE THREAD

**Issue by Tfarcenim** [NillerMedDild/Enigmatica4#23]
Here are some mod suggestions to help the pack feel a bit more fleshed out, the suggestions I'm about to list are unlikely to be replicated by another mod due to either mod dev absence or discontinuation.

[Metal Barrels](https://www.curseforge.com/minecraft/mc-mods/metal-barrels) mod that adds Iron Chest-style upgraded vanilla barrels that are much more FPS and TPS friendly than their chest counterparts.

[Angel Ring](https://www.curseforge.com/minecraft/mc-mods/angel-ring) Adds flight in a way similar to the old XU ring, with curios support built in.

[Dank Storage](https://www.curseforge.com/minecraft/mc-mods/dank-storage) you probably already know about this one but leaving it here for convenience.

[Anvil Tweaks](https://www.curseforge.com/minecraft/mc-mods/anvil-tweaks) makes the anvil slightly less terrible, compatible with Apoth.

[Cursed Earth](https://www.curseforge.com/minecraft/mc-mods/cursed-earth/) Good solution for compact mob farms that don't break the server, highly configurable.

**Comment by NielsPilgaard** [comment]
Thank you for the suggestions, I'm considering them all :)

**Comment by NielsPilgaard** [comment]
I will keep the others in mind, but I won't be adding them atm.
