### ISSUE TITLE
Evaluate The Lost Cities

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica4#230]
https://www.curseforge.com/minecraft/mc-mods/the-lost-cities

**Comment by NielsPilgaard** [comment]
Haven't found a single City yet, with the only cities preset.

**Comment by Darkere** [comment]
Not having any issues? I selected only cities and spawned inside a city on both my attempts.

**Comment by NielsPilgaard** [comment]
Hmm.. I must be doing something wrong. I've tried 7 times, still no city.

**Comment by Darkere** [comment]
oh. Where are you selecting the preset?

**Comment by NielsPilgaard** [comment]
The LC button in the world picker.
Edit: I'll try again tomorrow :P

**Comment by Darkere** [comment]
Can only imagine you pressed cancel instead of done then :)

But I'm getting massive tps problems when world genning so not quite ready yet :/

**Comment by NielsPilgaard** [comment]
I did press done unfortunately :(

Ah alright, I'll hold off on my attempts then, thanks.
