### ISSUE TITLE
Corail Tombstone issue or feature?

### ISSUE THREAD

**Issue by TwoPointInfinity** [NillerMedDild/Enigmatica4#233]
**Modpack version**
Enigmatica 4 v0.3.7

**Issue**
Line 114 of the tombstone-common.toml config file is set to "chance_soul = 0"
Line 196 also has grave dust disabled, there's no other way of obtaining this item besides the advancement rewards.
This has been changed from 100 (default:100) and pretty much renders the tombstone mod useless besides the fact that we can have gravestones. 
Is this intended? Was this mod only wanted to have graves? 
This mod is a nice addition to the modpack and would be fun with it's additions like upgrading your grave's key and decorative graves. I understand disabling some of the items like the tablets and scrolls if its not what you aim the pack to be.

**Logs**
No crash report or logs applicable.

**Comment by NillerMedDild** [comment]
Yep this intended, I just wanted graves. I believe you can still get grave dust from zombies though, and decorative graves should be accessible without grave dust.

**Comment by TwoPointInfinity** [comment]
Just a little information on the mod in case you would want to consider using it for it's other features. 
Souls are pretty uncommon, coming only from decorative graves (which are all made from a marble where grave dust is needed) and right clicking one with your key will enchant it and allow you to teleport to your grave where-ever it is (even in another dimension; configurable on line 28-29). Your key then disappears and your next key is not enchanted unless you do it again. Souls can be captured and saved in item form as well to make it easier. Souls only have a 10% chance to spawn every 30 minutes on a grave by the default settings. But is is set it to 0% every 30 minutes.

**Comment by NillerMedDild** [comment]
Thanks for the info, but I'd rather just have a grave mod with nothing extra :P

**Comment by Darkere** [comment]
Due to the advancements of the mods it is possible to increase the drop rate of grave's dust using the knowledge of death features.

**Comment by NillerMedDild** [comment]
God dammit. Thanks for letting me know.
