### ISSUE TITLE
Drinking wormhole potion crashes the game

### ISSUE THREAD

**Issue by TwoPointInfinity** [NillerMedDild/Enigmatica4#234]
**Modpack version**
Enigmatica 4 v0.3.7

**Important information**
 I am in a LAN game and all players are consider op with cheats enabled.
The players i am LAN connected with are not on the same network as me, i am port forwarding the LAN port that minecraft picks for the LAN game and they join with the new 5 numbers via my direct IP every time.

**Issue**
Drinking a Wormhole potion from bountiful baubles crashes the game.
If this is a mod specific crash I'm sorry for putting this in the wrong place, and where can i report the issue?

**Logs**
https://pastebin.com/DA6vsTLw

**Comment by NillerMedDild** [comment]
Thanks for the report, even if this is mod specific, it would be perfectly alright to post it here :) 

I'll have a look at it later today and relay the issue.

**Comment by Darkere** [comment]
https://github.com/CursedFlames/BountifulBaubles/issues/21
