### ISSUE TITLE
Add Nature's Compass

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica4#235]
https://www.curseforge.com/minecraft/mc-mods/natures-compass

**Comment by geoffmca** [comment]
FYI compass is currently uncraftable, its fixed in the next release, which some come during the next Enigmatica release.

**Comment by NielsPilgaard** [comment]
It's not uncraftable, I made a recipe for it.

**Comment by geoffmca** [comment]
https://github.com/MattCzyr/NaturesCompass/commit/a96a85184ba6347d795cffc1d8ec595a393cc478

Version 1.8.2 fixes an uncraftable bug (the recipe is there but the crafting table wont output anything) tried it in Refined Storage Grid, Crafting Table and Crafting Workbench.

I spawned one in creative and it worked as expected.

**Comment by NielsPilgaard** [comment]
Oh I see, thanks. I thought a CraftTweaker recipe would work regardless

**Comment by geoffmca** [comment]
Confirmed its now working as expected.
