### ISSUE TITLE
Items no longer go up creates mechanical belts

### ISSUE THREAD

**Issue by MaraVonBagel** [NillerMedDild/Enigmatica4#237]
**Modpack version**
0.4.1
**Issue**
Dropped items no longer go up the mechanical belts of create on version 0.4.1.
I downgraded my version to 0.3.6 and they work properly on that version.

A picture of the block that has stopped moving up the mechanical belt.
![Conveyer with an item stuck](https://user-images.githubusercontent.com/59418834/71644650-7f8c4280-2c91-11ea-92c0-5e4c724ab3be.JPG)

I have never submitted a bug report before, so I hope this is ok.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thanks for the report, it's definitely ok :)

Create wasn't updated between those versions, so this will probably be a hard one to track down, but I'll give it a shot.

**Comment by geoffmca** [comment]
I did some testing of this (not sure if  you have time, thought I would be helpful). I'm not actually sure this is a bug, I tested it in 0.3.4, 0.3.6 and 0.4.1.
To fix it I replaced the water wheel with a motor, blocks then go up the conveyor belt as expected. I'm not sure if there was a change in the force coming from water wheels but I couldnt get it to work in my 0.3.4 where using a motor it worked 100% in all 3 versions. So it looks like its down to lack of rotational force. 

That being said on my server 0.4.1 I saw intermittent stuttering (it would work fine for 1 block then not the next), not sure if it was down to lag or how the machines work. In my world i'm using refined story and factory droppers to do the same thing. 

*did some more testing in SMP* 

Using a motor and going from lower (flat conveyor) to diagonal is working 100% of the time to move the items up the ramp. Can you try using a motor and see if that solves it?
![2020-01-03_20 03 34](https://user-images.githubusercontent.com/12724063/71757488-55d74500-2e64-11ea-800d-6fffc419208f.png)

**Comment by NielsPilgaard** [comment]
Thanks a lot for the help! This issue sounds like its an intended feature of Create.
