### ISSUE TITLE
Add AuthMe

### ISSUE THREAD

**Issue by axieum** [NillerMedDild/Enigmatica4#238]
I just released **[AuthMe](https://www.curseforge.com/minecraft/mc-mods/auth-me)** a session re-validation mod.

> Authenticate yourself in Minecraft and re-validate your session

_This is a `1.14.4` equivalent to the popular **ReAuth** by TechnicianLP._

I wasn't going to recommend it, as a client side mod, but saw you had included ReAuth in other Enigmatica packs.

**Comment by NielsPilgaard** [comment]
Thanks for letting me know, I'm pretty sure I'll add it :)
