### ISSUE TITLE
Evaluate ProjectE and Quatum Storage

### ISSUE THREAD

**Issue by josemoncab** [NillerMedDild/Enigmatica4#239]
https://www.curseforge.com/minecraft/mc-mods/projecte

https://www.curseforge.com/minecraft/mc-mods/quantumstorage
Quantum storage give to us the possibility to storage massive amounts of 1 item type or fluid type in one block

**Comment by Discomanco** [comment]
I'm always against ProjectE, because I don't like ProjectE.
Quantum Storage, not sure we need a dedicated mod for it. We have Storage Drawers, and Black Hole Units is from Industrial Foregoing, which is already in (or BHUs may be added later)

**Comment by NielsPilgaard** [comment]
I'm not a really fan of ProjectE either, there's not really a place for it in a kitchen sink pack, it'll outclass everything else.

Quantum Storage is a nope, because of duplicate future content, as Disco says.

Thanks for the suggestions anyhow!
