### ISSUE TITLE
Crash when access drawer's invetory form crafting station

### ISSUE THREAD

**Issue by josemoncab** [NillerMedDild/Enigmatica4#240]
**Modpack version**
0.4.1

**Issue**
Duplication (I still try it but this isnt all time that i try):
If you have a crafting station next to drawer and open the station, you can pick up items from drawer and duplicate them. (Not all the time)
    _Video_: 
_If i cant replicate the duplication bug, i edit this to remove the duplication. Only happened 1 time_

Crash:
If you have a crafting station next to drawer and open the station and shirft-click the items in drawer's inventory or pickup and return to drawer, the game crash
    _Video shirf-click_: https://youtu.be/wqn4ZZofKpk
    _Video pickup and return_: https://youtu.be/NP1usxwV8OA

**Logs**
Crash report shirf-click: https://pastebin.com/N9iW2m3n
Crash report pickup and return: https://pastebin.com/vXdFGP4x

PD: In one of this crash, drawer's inventory clear

**Comment by NielsPilgaard** [comment]
Thanks for the report, I've relayed it to the Storage Drawers issue tracker.
