### ISSUE TITLE
Add Inventory Tweaks Reborn

### ISSUE THREAD

**Issue by Landmaster** [NillerMedDild/Enigmatica4#241]
https://www.curseforge.com/minecraft/mc-mods/it-reborn

To replace Inventory Sorter

**Comment by NielsPilgaard** [comment]
What does it offer that Inventory Sorter does not?

**Comment by Landmaster** [comment]
- Automatic itemstack and tool replacement
- More configurable player sorting (e.g., you can designate slot 1 in your hotbar to your sword)

The bigger question, IMO, is what does *Inventory Sorter* offer that Inventory Tweaks does not?

**Comment by NielsPilgaard** [comment]
You had me at `Automatic itemstack and tool replacement` <3

**Comment by douyabian** [comment]
Yesss slot blacklisting for sorting!

**Comment by NielsPilgaard** [comment]
I'm unable to bind the Sort Inventory hotkey to Middle Click, is that a known issue? It works just fine with the default `'` and  `r`, even though `r` is conflicting.

**Comment by Landmaster** [comment]
- I haven't implemented the middle click binding yet. I'll probably do that next release.
- The sort key is not bound to "R" by default; it's bound to GRAVE (for chest sorting) and BACKSLASH (for player sorting)

**Comment by NielsPilgaard** [comment]
Ah so which inventory is sorted is not dependant on where the cursor is, like in Inventory Tweaks?

**Comment by Landmaster** [comment]
Nope! I decided to implement it differently because of how *\*\*\*\*ing* annoying it is to try to press "R" in order to pull up a JEI recipe, only to have it perform an undesirable sort instead.

**Comment by NielsPilgaard** [comment]
Fair enough, I really liked that feature though, remembering keybindings is tough.
Could you make the sorting and item replacement parts of the mod togglable through the config? :)

**Comment by Landmaster** [comment]
I'll add that to my todo list; it'll probably be implemented in the next few days or so.

**Comment by NielsPilgaard** [comment]
Sounds good!

**Comment by Landmaster** [comment]
Features added in [0.5.0](https://www.curseforge.com/minecraft/mc-mods/it-reborn/files/2855060)

**Comment by NielsPilgaard** [comment]
Awesome, thank you.
