### ISSUE TITLE
PSA: Flight

### ISSUE THREAD

**Issue by douyabian** [NillerMedDild/Enigmatica4#242]
**Modpack version**
0.4.1

**Issue**
Known conflict between angelring mod and everlastingabilities' flight. Angelring prevents everlasting flight from working, just thought to give you guys a heads up

**Comment by NielsPilgaard** [comment]
Thanks for the PSA!
Linking the issue.
https://github.com/DenisMasterHerobrine/AngelRing/issues/2

**Comment by DenisMasterHerobrine** [comment]
Fixed in 1.1.0-pre2 of the mod. There is a rewrite coming out soon, so there are a temporarily fix for the mod.
https://www.curseforge.com/minecraft/mc-mods/angel-ring/files/2856232
