### ISSUE TITLE
Recipes for Quark/Vanilla stone types

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica4#245]
Would be nice to be able to get them in bulk without having to find the correct biomes.

**Comment by HermitForge** [comment]
add them as a chisel version of cobblestone
also maybe add chisel if not already in the pack

**Comment by Discomanco** [comment]
Man, giving me the hope that Chisel is actually updated for 1.14.4.  
Sadly it is not

**Comment by HermitForge** [comment]
I looked it up, and it said that chisel would work for 1.14
I looked at it again, and it said that they are planning to update it
