### ISSUE TITLE
InstaCrash when starting the pack 

### ISSUE THREAD

**Issue by smmailik** [NillerMedDild/Enigmatica4#246]
**Modpack version**
0.4.1

**Issue**
I've downloaded the pack yesterday, started it and played about an hour then i had to go and I closed it . After when I've attempted to open it again the client crash every time . 
I've deleted the instance and redownloaded the pack many times and the game won't start and just crash every time 

**Logs**
https://pastebin.com/Di5VB5q9

**Comment by NielsPilgaard** [comment]
It looks like Forge has gone missing for some reason, I suggest you try to change the Forge version of the instance to 28.1.108 and then back to 28.1.109
