### ISSUE TITLE
Sound Issues After Exiting The End

### ISSUE THREAD

**Issue by Diatom86** [NillerMedDild/Enigmatica4#247]
**Modpack version**
0.3.7

**Issue**
After leaving the end and getting back to the overworld, all
passive and aggressive mob sounds stop working. Also my weapons don't make any sound when hitting mobs. Re-logging corrects it though.

**Logs**
(Hopefully I did this right. First time reporting anything)
[latest.log](https://github.com/NillerMedDild/Enigmatica4/files/4023873/latest.log)

**Comment by NielsPilgaard** [comment]
Please update to see if that resolves the issue, current version is 0.4.1

**Comment by Diatom86** [comment]
Updated to 0.4.1 and the issue is resolved.

**Comment by NielsPilgaard** [comment]
Excellent, thanks for the update.
