### ISSUE TITLE
[Request] Add BonsaiTrees 2

### ISSUE THREAD

**Issue by tonyvans** [NillerMedDild/Enigmatica4#251]
**Modpack version**
BonsaiTrees-2.0.1.32.jar

https://www.curseforge.com/minecraft/mc-mods/bonsai-trees

So we can grow trees in pots

Thank you for considering it.

**Comment by NielsPilgaard** [comment]
Done and done :)

**Comment by tonyvans** [comment]
thank you

**Comment by geoffmca** [comment]
Although mod is in change log, it didnt make it into the package (or atleast not for me).

**Comment by NielsPilgaard** [comment]
Woops :P I'll get that sorted, thanks
