### ISSUE TITLE
PSA: Portality portals X Persistent Bits Chunkloader

### ISSUE THREAD

**Issue by douyabian** [NillerMedDild/Enigmatica4#252]
**Modpack version**
v0.4.1

**Issue**
Portality portals removes persistent bits forceloaded chunks, from what I know the current version of persistent bits uses /forceload commands to chunkload, however for some reason after activating a Portality portal, the chunk that the Portal Controller is in will be removed from forceload

**Logs**
No log really, just an observation that was causing my game to freeze up due to entities not processing

**Comment by douyabian** [comment]
EDIT: Just realised that the mod removes the chunk the portal controller is when it is not dialed/running, hence if you hit "dial once" it will remove the chunk from the forceload list

in hindsight, it seems like using the forceload command for chunk loading will require some vanilla chunkloading knowledge, especially with regards to lazychunks/entity processing chunks

**Comment by NielsPilgaard** [comment]
Thanks for the report, I relayed it :)

**Comment by NielsPilgaard** [comment]
This will most likely not be solved, as the mod is no longer received updates on 1.14.4 as far as I know.
