### ISSUE TITLE
Storage Drawer

### ISSUE THREAD

**Issue by MissGomez1** [NillerMedDild/Enigmatica4#254]
**Modpack version**
Enigmatica 4 version 0.4.1

**Issue**
went to go crate a 2x2 drawer and it tells me to use the same crafting recipe for a single drawer using oak wood.

**Logs**
![drawer](https://user-images.githubusercontent.com/59706230/72096979-5b5fdf80-32e9-11ea-828a-9941cff8d85b.png)

**Comment by NielsPilgaard** [comment]
So it does, my bad! I'll get that fixed
