### ISSUE TITLE
Mod Suggestion -> Astral -- Astral Projection Mod!

### ISSUE THREAD

**Issue by drizzs** [NillerMedDild/Enigmatica4#257]
Mod Suggestion -> Astral -- Astral Projection Mod!
https://www.curseforge.com/minecraft/mc-mods/ma-astral

This mod is new and might have some compatibility issues, if you're unable to add it to your pack and you like the idea, i suggest you keep an eye on it, the mod creator is working really hard on bringing something new to the mod community!

**Comment by NielsPilgaard** [comment]
It doesn't add much at the moment, so it's a no, but I will keep an eye on it :)
