### ISSUE TITLE
Suggestion: Ender Tanks

### ISSUE THREAD

**Issue by douyabian** [NillerMedDild/Enigmatica4#259]
https://www.curseforge.com/minecraft/mc-mods/endertanks

An alternative fluid tank with variable storage size, pump speed and dimensionality

**Comment by NielsPilgaard** [comment]
Duplicate of #222 
It's still too buggy I'm afraid.

**Comment by douyabian** [comment]
Right, my bad, had a bad search and didn't see it! unfortunate that it's still buggy
