### ISSUE TITLE
Bonsai Tree 2 not working on Server

### ISSUE THREAD

**Issue by AshuraxNinja** [NillerMedDild/Enigmatica4#261]
**Modpack version**
0.4.3

**Issue**
Anytime I try using the bonsai tree, whether it's hopping bonsai or regular, it continuously says I need to try different soil. I've tried grass and dirt. If I go single player, it works without hassle. Also have an issue with blocks being deleted when trying to autofill.

**Logs**
No log to reference from.

**Comment by NielsPilgaard** [comment]
Thank you for the report, this issue is fixed and will be a part of 0.4.4 :)
