### ISSUE TITLE
Inventory refill deletes extra stacks

### ISSUE THREAD

**Issue by WindFreaker** [NillerMedDild/Enigmatica4#266]
**Modpack version**
0.4.3

**Issue**
I placed the last block of sand from my inventory and the other 6 stacks disappeared, only placing one stack in my hand, effectively deleting 5 stacks. This issue is repeatable through saving and quitting and a complete restart of the client. I have not tested with other items/blocks.

**Logs**
No crash/logs.

**Comment by NielsPilgaard** [comment]
Thanks for the report, I will test it immediately.

**Comment by NielsPilgaard** [comment]
I cannot replicate this. Were the Sand stacks that disappeared just sitting in your inventory?

**Comment by WindFreaker** [comment]
Yes. I can record a short video or something to help with the report. I have repeated it consistently in my testing.

**Comment by NielsPilgaard** [comment]
Ah nevermind, I updated Inventory Tweaks locally. This appears to have been fixed in the mod.

**Comment by NielsPilgaard** [comment]
I'll get an update out asap, thanks again.

**Comment by NielsPilgaard** [comment]
Update 0.4.4 is now available, which fixes this issue :)
