### ISSUE TITLE
Snow and Ice in all biomes.

### ISSUE THREAD

**Issue by xxtakuraxx** [NillerMedDild/Enigmatica4#268]
**Modpack version**
0.4.4

**Issue**
Not sure if it is a mod or serer bug, but Ice is forming and it is snowing in biomes where it isnt supposed to be. IE I am watching ice form on the edge of a desert biome as I am writing this and it was snowing in a plains biome.

**Logs**

**Comment by xxtakuraxx** [comment]
my friend had a huge ocean near him and its almost entirely ice now and theres no snow biomes around.

**Comment by NielsPilgaard** [comment]
That included by the mod Serene Seasons, and is intended for the most part - is it an issue? :)

**Comment by xxtakuraxx** [comment]
Does all of the ice/snow melt when the seasons change? I am new to that mod. It can be a pain if you start during winter time and crops die, is about it.

**Comment by xxtakuraxx** [comment]
I just wasnt expecting everywhere I go to start turning into ice. I thought something was bugged.

**Comment by NielsPilgaard** [comment]
Understandably! It should melt after about 7 Minecraft days, but I meant to turn the water to ice thing off iirc.

**Comment by xxtakuraxx** [comment]
That would be a plus. I was watching water turn to ice in the middle of a desert lol, but ok, its just a lack of my knowledge of the mod.

**Comment by NielsPilgaard** [comment]
I think the game should inform you about seasons, so I'll mark this as a bug and see what I can do :)

**Comment by xxtakuraxx** [comment]
on a side note, loving the pack so far, but no I dont remember seeing any in game info about the seasons.

**Comment by xxtakuraxx** [comment]
new update. I started a new server from scratch, switched to 4.4. Started in the spring time, set snow/ice to false and ice is still forming in all of the biomes.

**Comment by NielsPilgaard** [comment]
Thanks for testing, I'll throw them a bug report this evening, unless you beat me Tobit :P

**Comment by xxtakuraxx** [comment]
I havent sent anymore reports, its all yours! lol

**Comment by NielsPilgaard** [comment]
Done! https://github.com/Glitchfiend/SereneSeasons/issues/227

**Comment by NielsPilgaard** [comment]
I used Enigmatica 5 to test it, same issue.

**Comment by NielsPilgaard** [comment]
I removed the mod, so this is "fixed" :P
