### ISSUE TITLE
[Request] Add TrashSlot (or some other trash type mod)

### ISSUE THREAD

**Issue by tonyvans** [NillerMedDild/Enigmatica4#269]
**Modpack version**
TrashSlot_1.14.4-10.4.8.jar

https://www.curseforge.com/minecraft/mc-mods/trashslot

Because who doesn't like being able to dump the excess junk. 

Thank you for considering it.

**Comment by xoxzerkxox** [comment]
there is the trash from cyclic. but a trash in your inventory woud be nice.

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion, I'll think about it :)

**Comment by tonyvans** [comment]
besides being convenient  I suggested it mostly because the mining laser void and nor does the rftools builder in a quarry capacity seem to void anything and the infinity drill doesn't have one at all (or I just can't figure it out and have found nothing online) I end up with so much cobble and stone and it is tedious to dump it one stack at a time. (You don't realize how much you miss the extra utilities trash can until it is gone, and the mod author stated in a post it won't be ready for 1.14.4 for a long time) Either way, Thank you for thinking about it.

**Comment by douyabian** [comment]
modular routers has a trash module, couple it with stack + speed and you'll have a trash can effectively as well

**Comment by tonyvans** [comment]
> modular routers has a trash module, couple it with stack + speed and you'll have a trash can effectively as well

Interesting I did not know about that, is it portable? (for when mining and your inventory is full?)
