### ISSUE TITLE
Recept confict. (same recept 2 different items)

### ISSUE THREAD

**Issue by xoxzerkxox** [NillerMedDild/Enigmatica4#270]
**Modpack version**
0.4.4

**Issue**
i tried to craft amethyst sword from Mystical mod (7 hearts / 1.6 speed ) . however the same recept gives the amethyst sword from Blue power mod (6 hearts / 2.6 speed ) .

And while looking deeper on it All the Mystical amethyst tools that you can craft with amethyst has a conflict with the Blue power variable.

Possible solution.
remove the 1 of the variable ( probably the mystical mod one so the Sapphire / ruby / malachite so there is no stat difference in "gems" )

**Comment by NielsPilgaard** [comment]
I'll get that fixed, thanks :)
