### ISSUE TITLE
Crash: Excavate IV Enchant

### ISSUE THREAD

**Issue by mr-e12345** [NillerMedDild/Enigmatica4#272]
**Modpack version**
Enigmatica 4 0.4.4
default configs

**Issue**
Enchanted a Blue Power ruby shovel with enchant table, obtained Excavate IV (Cyclic) and Fortune III (Vanilla) enchants. Usage of the shovel appears to create ghost blocks of any dirt/grass blocks excavated, and the game crashes when interacting with the ghost blocks, with the following message:

The game crashed whilst ticking entity
Error: java.lang.ArrayIndexOutOfBoundsException: 4

I have tested Excavate I, II, and III in a second world with Fortune, all work correctly. Excavate appears not to play nicely with whichever mod is increasing the enchant level at enchanting tables.

**Logs**
Pastebin:
https://pastebin.com/0XkLKmp9

**Comment by NielsPilgaard** [comment]
Thank you for the excellent report :)

Apotheosis is responsible for changing enchants, and the max level for all enchantments can be modified in the config, so it's an easy fix :D
