### ISSUE TITLE
[Mod Request] Add Server Tab Info to the pack

### ISSUE THREAD

**Issue by Crimix** [NillerMedDild/Enigmatica4#273]
I think that [Server Tab Info](https://www.curseforge.com/minecraft/mc-mods/server-tab-info) would be a nice addition at this stage. It is both for clients or/and servers.

Its purpose is to show tps and mean tick time of the server (also internal server for SP) in a nice and easy way to understand by modifying the player tab list and introducing a new player tab like list with all loaded dimensions and their tps info.

P.S. I am author, but I really think it could help at this sorta unstable time
This also applies for the 1.15 modpack

**Comment by NielsPilgaard** [comment]
I agree, looks like a great addition :)
