### ISSUE TITLE
Recipe Conflict (Raw Pork)

### ISSUE THREAD

**Issue by Rosate** [NillerMedDild/Enigmatica4#275]
**Modpack version**
0.4.4

**Issue**
Raw bacon (Simple Farming) and pig fat (Extended Lights) are both crafted using 1 raw pork. When used, the recipe yields raw bacon, rendering pig fat unobtainable.
(The wax that pig fat is used to create can still be obtained by smelting sweet berries, so access to Extended Lights features is still possible despite the issue)

**Comment by NielsPilgaard** [comment]
Thanks for the report, I'll get that fixed :)

**Comment by NielsPilgaard** [comment]
I would like to fix this by making a bacon recipe that takes durability from a knife and Raw Porkchop, however that doesn't seem possible with CrT at the moment.

Once available, this will be fixed :)

```js
for knife in <tag:forge:fillet_knife>.items {
    addShapeless(<item:simplefarming:raw_bacon> * 2, [<item:minecraft:porkchop>, knife.transformDamage(1)], true);
}
```
