### ISSUE TITLE
Join Server error on 0.1.1

### ISSUE THREAD

**Issue by ArbitraryHubris** [NillerMedDild/Enigmatica4#28]
**Modpack version**
0.1.1

**Issue**
minor issue - when joining my server (using server files with forge installed to match the clientside) I see a red X on server connection screen saying things are not compatible between client and server, but it connects fine - no errors.

![Server Connect](https://user-images.githubusercontent.com/8292929/66720239-d172aa00-edbf-11e9-9e32-5cd2dbfbebee.png)

You can try against my server at e4.joyousapathy.com

**Comment by NielsPilgaard** [comment]
That is caused by "missing" client mods on the server :)

**Comment by ArbitraryHubris** [comment]
It's sad that it shows an error, though.  defeats the purpose of the forge check that it doesn't consider that some mods are client-only.  Though, I guess that's more difficult now that you don't have client and server versions of mods any longer.

**Comment by NielsPilgaard** [comment]
client-only isn't a thing anymore I think :/ but yeah it sucks.
