### ISSUE TITLE
Can not launch the modpack

### ISSUE THREAD

**Issue by dustojnikhummer** [NillerMedDild/Enigmatica4#280]
**Modpack version**
0.44

**Issue**
Crash on startup, both Twitch and MultiMC

**Logs**
MultiMC launcher just dies instantly https://pastebin.com/ZxhvmTai
Twitch crashes instantly as well https://pastebin.com/PgAYZywc

**Comment by NielsPilgaard** [comment]
Try using the GDLauncher :)

**Comment by dustojnikhummer** [comment]
> Try using the GDLauncher :)

Will try. Sorry if it sounded like a support request (bad bot), I'm trying to report his as an issue.

**Comment by NielsPilgaard** [comment]
I know it's an issue, we just can't do anything to fix it, it's a Twitch issue :/
