### ISSUE TITLE
Simply Backpacks Deleting items

### ISSUE THREAD

**Issue by JaMegaHit** [NillerMedDild/Enigmatica4#282]
**Modpack version**
0.4.4

**Issue**
Backpacks from Simply Backpacks are a bit broken.. Why? Well the first time when you put some items in it it's fine, but when you try to add to those existing items (after closing) the amount you added just disapears after re-opening.

**Comment by NielsPilgaard** [comment]
O_o I'll have a look asap.

**Comment by NielsPilgaard** [comment]
I'm afraid I didn't have time until just now, reported the issue to the mod developer. Thanks for the report!

**Comment by Cheata** [comment]
I have found that the backpacks seem to be usable in their current condition if you leave the auto collect turned off and don't keep them on your active hotbar, Im still leary about putting anything except cobblestone in them however.

**Comment by NielsPilgaard** [comment]
Oh interesting, they don't void things under those conditions?

If so, could you please write that in the issue I linked? :)

**Comment by Cheata** [comment]
experience added to linked issue as requested :)
