### ISSUE TITLE
Dangerous Bug

### ISSUE THREAD

**Issue by silverwolf1793** [NillerMedDild/Enigmatica4#285]
**Modpack version**
0.4.4

**Issue**
I was using some belt funnels and some chests, I removed the chest and this immediately crashed the game, now I cannot log into that world without crashing the game too

**Logs**
Replaced your log with a link (please use a link in the future)
https://gist.github.com/NillerMedDild/51e97a35d5c250925dd183c21de30b07

**Comment by NielsPilgaard** [comment]
Thanks for the report, I'll relay it asap.

**Comment by silverwolf1793** [comment]
> Thanks for the report, I'll relay it asap.

No problems, to make your task easier I'll explain what it was (I fixed my map)

I just found out what I did, I pushed a piston straight into the belt funnel to push items and that did it


edit: NVM found the problem

**Comment by NielsPilgaard** [comment]
So you essentially tried to move the Belt Funnel with a Piston? Or did you just push items to it?

**Comment by silverwolf1793** [comment]
[piston][belt][belt funnel][chest]
my idea was to try "pushing" the items from the belt into the belt funnel to "side load" from the belt, apparently that killed it for some reason

**Comment by NielsPilgaard** [comment]
Ah I see. Pushing tile entities with a piston isn't the best idea :P
