### ISSUE TITLE
Bonemeal appears to be unusable

### ISSUE THREAD

**Issue by jarrodcabalzar** [NillerMedDild/Enigmatica4#287]
**Modpack version**
0.4.4

**Issue**
When trying to bonemeal plants, specifically mystical petals to grow tall flowers, bonemeal does nothing when you right-click. I haven't been able to identify any config options that might affect or cause this so I'm assuming it's probably a bug in one the mods.

Absolutely love the pack by the way, keep up the great work!

**Comment by jarrodcabalzar** [comment]
Oh, I just tried again and it worked. Guess it's part of Serene Seasons? Kinda annoying for Botania though.

**Comment by NielsPilgaard** [comment]
Yeah it is, and we're removing Serene Seasons :)
