### ISSUE TITLE
^M newlines in shellscripts

### ISSUE THREAD

**Issue by scederqv** [NillerMedDild/Enigmatica4#289]
**Modpack version**
0.4.4

**Issue**
Carriage return characters in linux shellscripts in the server pack.
They need to be removed. Here's a spell for that:
sed -i -e 's/\r$//' *.sh

**Comment by NielsPilgaard** [comment]
Why do they need to be removed? :)

**Comment by Benno1308** [comment]
Because otherwise some shells will error out,
e.g.
```
master[/DATA2/mc_tmp]$ ./server-start.sh
-bash: ./server-start.sh: /bin/bash^M: bad interpreter: No such file or directory
```

**Comment by NielsPilgaard** [comment]
I'll try to find a way around it, but I didn't make either start script, so no promises :D

**Comment by scederqv** [comment]
I'll make a pull request.

**Comment by NielsPilgaard** [comment]
Much appreciated!
