### ISSUE TITLE
Server files are missing all top-level server-only files

### ISSUE THREAD

**Issue by ArbitraryHubris** [NillerMedDild/Enigmatica4#29]
**Modpack version**
v0.1.1

**Issue**
Server files just include the 4 main folders you need to replace, but no server.properties, no forge installer, no ServerStart.sh, etc.  

![Contents of Enigmatica4Server-0.1.1.zip](https://user-images.githubusercontent.com/8292929/66720328-d2580b80-edc0-11e9-8ee6-753e6b13902c.png)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Look in the development folder :)

**Comment by NielsPilgaard** [comment]
However, that's not exactly optimal, fixed for next release (0.1.4)
