### ISSUE TITLE
settings.cfg full of semicolons.

### ISSUE THREAD

**Issue by scederqv** [NillerMedDild/Enigmatica4#290]
**Modpack version**
Server 0.4.4

**Issue**
settings.cfg syntax error. The lines are erroneously ending with semicolons. 

Error: Unable to access jarfile forge-1.14.4;-28.1.109;

**Comment by NielsPilgaard** [comment]
They are required by the bat script. How are you using the file?

**Comment by scederqv** [comment]
In most ux-like shells, variables are just written as 

MYVAR=variable.cfg

These variables include a semicolon delimiter, presumably for windows systems, which prevents the script from working in linux.

The pull request separates the windows config from the linux config.

**Comment by NielsPilgaard** [comment]
Thanks for the explaination :)
