### ISSUE TITLE
Just Enough Resources (JER) not working 

### ISSUE THREAD

**Issue by KICKACE95** [NillerMedDild/Enigmatica4#293]
**Modpack version**
0.4.5

**Issue**
Just Enough Resources (JER) is not working at all for me. its like it not even installed but it is in the mod list. also updated it to the newest version of JER but it did nothing

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Possibly silly question, but what do you expect it to do?

**Comment by KICKACE95** [comment]
mob drop,Dungeon Loot,Plant Drops tables and Ore Gen graph? idk if every thing is currently ported but for me nothing is for me.

**Comment by NielsPilgaard** [comment]
It's missing quite a bit still, not sure what should and what shouldn't be working tbh.

**Comment by NielsPilgaard** [comment]
It is indeed a bug, except for ore graphs, which are not implemented yet.
