### ISSUE TITLE
Infinity Drill doesn't power or fluid

### ISSUE THREAD

**Issue by silverwolf1793** [NillerMedDild/Enigmatica4#294]
**Modpack version**
0.4.5

**Issue**
The infinity drill once you have input energy and biofuel its free to use as it will stop using any of those two, also when using tanks or pushing any kind of liquid into powah machines it voids it, if you use for example a tank within the magmatic generator it will take a single bucket of lava and void the rest, also there is not a good system yet for handling liquids from what I've seen so using a lot of mods becomes a painful experience... for example using the pump from silent machines to extract lava becomes very tedious as it only uses buckets but there's no simple way to extract the liquid from the bucket and store it into a tank

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by silverwolf1793** [comment]
Also the only fluiduct on the current pack I feel its very expensive, an ender pearl and two tanks for a single fluiduct its way too expensive for early game

**Comment by NielsPilgaard** [comment]
I feel like this should be 3 issues? :P

**Comment by silverwolf1793** [comment]
haha probably sorry for stacking them

**Comment by NielsPilgaard** [comment]
Oh well, I'll look into them.
Edit: Thanks for the report(s)

**Comment by silverwolf1793** [comment]
sure! any doubts or help I could bring just ask and I'll reply

**Comment by Frogwisard1984** [comment]
i agree that having only the one usable way to move fluid is kinda hard and expensive. could you add the cyclic piping maybe?

**Comment by Darkere** [comment]
Xnet has been added since.

**Comment by Frogwisard1984** [comment]
> Xnet has been added since.

yes but i find that to be confusing for people new to xnet. I've messed with it but its still got a lot of functions i'm not sure about. thanks for taking the time to respond.

**Comment by NielsPilgaard** [comment]
Infinity Drill issue has been fixed in the 1.15.2 version, I'm not sure it'll make it to 1.14 though.
I have reported the Powah/Large Fluid Tank issue here: https://github.com/owmii/Powah/issues/54
The Fluid Pipe is indeed insanely expensive, I've fixed that.

**Comment by Frogwisard1984** [comment]
> Infinity Drill issue has been fixed in the 1.15.2 version, I'm not sure it'll make it to 1.14 though.
> I have reported the Powah/Large Fluid Tank issue here: [owmii/Powah#54](https://github.com/owmii/Powah/issues/54)
> The Fluid Pipe is indeed insanely expensive, I've fixed that.

Thank you so much! An ender pearl is really hard to come by right now. I hope that's what you changed... Does this auto update for us on the twitch loader?

**Comment by NielsPilgaard** [comment]
That is indeed what I changed. The will be a little up arrow next to the modpack's start button when the update is available :)
