### ISSUE TITLE
Minecolonies building tool doesn't show huts when placing down.

### ISSUE THREAD

**Issue by DmasterD** [NillerMedDild/Enigmatica4#296]
**Modpack version 0.4.8 on a multiplayer server**

**Minecolonies building tool doesn't show huts when placing down.**
The first hut to build is a Builders's Hut. 
Whenever this hut is selected with the building tool, just the block is shown, not the whole building.
The same applies to all other huts, like citizen or farm.

I'm suspecting it's a mod issue, but I've not found it anywhere yet.
The huts are selectable, but what you can't select with the building tool is the type, e.g. medievaloak.
Maybe the issue lies there (or I'm just using the building tool in the wrong way?).

**Comment by NielsPilgaard** [comment]
I suggest you ask on their Discord, it's going to take a few days before I have time to help I'm afraid :)

**Comment by DmasterD** [comment]
It might be https://github.com/ldtteam/minecolonies/issues/4344.
Although that issue is currently still open and being investigated.

**Comment by DmasterD** [comment]
It was something weird in my order of placing down a hut.
I can't reproduce it anymore, and there is no issue anymore for me.

**Comment by NielsPilgaard** [comment]
Cool :)
