### ISSUE TITLE
Client-side Crash - disconnected all players

### ISSUE THREAD

**Issue by ArbitraryHubris** [NillerMedDild/Enigmatica4#30]
**Modpack version**
0.1.1

**Issue**
sudden client-side crash.  I got a crashlog, referenced below.  The other player was disconnected.  The server still thought we were both connected and we both timed out trying to reconnect.  Server seems to be hung.  console /kick commands do not respond.  Normal minecraft console restart command is not responding.  Had to issue a kill command.

The log mentions iron jetpacks - neither of us are at a place where we have started using that mod.

**Logs**
https://pastebin.com/unGsqP5G

**Comment by ArbitraryHubris** [comment]
Update - after killing the server, the server never came back up.  It just never finished preparing spawn - sat at 0%.  Trying an upgrade to 0.1.3 and then starting the server up again.

**Comment by ArbitraryHubris** [comment]
Upgrading to 0.1.3 and letting forge remove iron jetpacks from our world solved the issue and our world starts up again.

**Comment by NielsPilgaard** [comment]
Same here, nice that you got it working!
