### ISSUE TITLE
Uraninite cannot be veinmined (by default)

### ISSUE THREAD

**Issue by Gerdathlete** [NillerMedDild/Enigmatica4#305]
**Modpack version**
Version 0.4.8

**Issue**
You cannot use veinminer on uraninite. Should be a simple fix in the config.

**Comment by Gerdathlete** [comment]
The item ids are all from powah.
uraninite_ore_poor
uraninite_ore
uraninite_ore_dense

**Comment by NielsPilgaard** [comment]
Thanks for the report, I'll get that done :)
