### ISSUE TITLE
Suggestion: Basic transfer pipe (items)

### ISSUE THREAD

**Issue by Gerdathlete** [NillerMedDild/Enigmatica4#306]
**Modpack version**
0.4.8

There currently doesn't seem to be a cheap item transfer pipe/conduit/duct.
Could you possibly add thermal dynamics or another pipe mod so that we can take full advantage of all the machines in the pack?

I don't think I can even automate ore doubling without using a storage system.

**Comment by NielsPilgaard** [comment]
The vast majority of mods haven't been updated to 1.14 yet, I can't add mods that don't exist :) 
We do have a cable mod, XNet
