### ISSUE TITLE
Crafting regular oak chests do not work

### ISSUE THREAD

**Issue by OGCrazyglue** [NillerMedDild/Enigmatica4#309]
**Modpack version**
0.4.8

**Issue**
Builder in Minecolonies cannot accept other chests than regular oak chest, and there is no recipe for the original oak chest

**Logs**
N/A

**Comment by NielsPilgaard** [comment]
You're supposed to be able to convert any chest to the original chest, is that not possible?

**Comment by Gerdathlete** [comment]
Yeah, you can convert any chest to a normal chest by just sticking it in a crafting table or the players inventory crafting. Isn't an issue.

**Comment by OGCrazyglue** [comment]
Pretty sure I tried that.. but I'll give it another go and get back to you
