### ISSUE TITLE
[Mod Request] Underground Biomes

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [NillerMedDild/Enigmatica4#31]
While Blue Power is already pretty good at making the underground feel less bland with its decorative worldgen like marble and stuffs, I still feel like there should be another incentive for players to explore the underground other than "ugh, gotta get more iron", so maybe something like [Underground Biomes](https://www.curseforge.com/minecraft/mc-mods/underground-biomes) would be a good addition to the pack.

That being said, it's still in a very early alpha, so it may or may not bork stuff, but hey, that's what pack betas are for, right?

**Comment by NielsPilgaard** [comment]
That is indeed what betas are for :P that being said, I'm not a big fan of mods that adds more stone types, I prefer the underground neat.

**Comment by NielsPilgaard** [comment]
What about something like https://www.curseforge.com/minecraft/mc-mods/yungs-better-caves, would that scratch the itch? :P

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-caves">Access denied | www.curseforge.com used Cloudflare to restrict access</a></strong></div></blockquote>

**Comment by MaxNeedsSnacks** [comment]
That seems like a good idea as well ^^

**Comment by NielsPilgaard** [comment]
I'd rather not add it to be honest :(

**Comment by MaxNeedsSnacks** [comment]
Ah that's fine, still thanks for considering ^^
