### ISSUE TITLE
Formatting of server-start.sh needs correction [Linux/Unix]

### ISSUE THREAD

**Issue by iInjection** [NillerMedDild/Enigmatica4#312]
**Modpack version**
Newest

**Issue**
some syntax errors (Dos/windows -> Unix)

**Logs**
```
server-start.sh: line 27: $'\r': command not found
server-start.sh: line 29: $'\r': command not found
server-start.sh: line 30: $'\r': command not found
server-start.sh: line 46: $'\r': command not found
server-start.sh: line 48: syntax error near unexpected token `$'in\r''
'erver-start.sh: line 48: `case "${unameOut}" in
```

solution on linux console: 
`sed -i -e 's/\r$//' *.sh`

Link to cleaned file: 
https://www.dropbox.com/s/uc7kmagwowfts11/server-start.sh?dl=0

EDIT: Explainiation of the command: replace all   $'\r'  with nothing in .sh files.

EDIT2: new error popped up: `server-start.sh: line 160: [: 0;: integer expression expected

EDIT3: Found another one regarding #311 : `Error: Unable to access jarfile forge-1.14.4;-28.2.3;`
Probably the syntax.

**Comment by NielsPilgaard** [comment]
Sounds to me like you need to revert to the original settings-linux file.

**Comment by iInjection** [comment]
Found it. from #311 your settings-linux file contained ONE space! 

![grafik](https://user-images.githubusercontent.com/22277062/76801501-19b25000-67d6-11ea-9d0b-85f3d1915f77.png)

( I marked it)

**Comment by NielsPilgaard** [comment]
Did removing that one space help?

**Comment by iInjection** [comment]
Okay I just tried some things

1. Removing all semicolons did not make a difference, my console still prints: 

```
Starting server
Error: Unable to access jarfile forge-1.14.4;
```

idk where the "1.14.4;" comes from, i checked both server-start.sh and serttings-linux.cfg. 

Console spitting out: 

`About to start server. Force re-install (y/n)?  n
server-start.sh: line 160: [: 0;: integer expression expected
Ping to Google DNS successfull
Ping to L4 successfull
server-start.sh: line 190: [: ./minecraft_server.1.14.4;: binary operator expected
`

I cannot find the errors there. 

I dropped both files form my server to here, if you would like to have a look: 

https://www.dropbox.com/sh/l8k2kh2bgwpr22u/AACzinFyozCK016oExYv3kpGa?dl=0

<blockquote><img src="https://www.dropbox.com/static/images/spectrum-icons/generated/content/content-folder_dropbox-large.png" width="48" align="right"><div>Dropbox</div><div><strong><a href="https://www.dropbox.com/sh/l8k2kh2bgwpr22u/AACzinFyozCK016oExYv3kpGa?dl=0">Files</a></strong></div><div>Shared with Dropbox</div></blockquote>

**Comment by NielsPilgaard** [comment]
At this point I think you should try a clean install :P

**Comment by iInjection** [comment]
Done. 

First thing: The server-start.sh is not properly formatted for Unix. 

Fix for it: i run sed -i -e 's/\r$//' server-start.sh

to clean up the errors found in my first post.  **+++FIXED+++**


2nd Problem: The Problem from before with 

> server-start.sh: line 202: settings_linux.cfg: No such file or directory

Fixed by editing the line to settings-linux.cfg.  **+++FIXED+++**

3rd Problem

> About to start server. Force re-install (y/n)?  server-start.sh: line 160: [: -eq: unary operator expected

I don't know how to fix this one. 

I am stopping here, so we can fix this together, so you can fix it on your side as well.

**Comment by iInjection** [comment]
I am stupid. 

> About to start server. Force re-install (y/n)? server-start.sh: line 160: [: -eq: unary operator expected

It wants me to put in y or n . since i did not provide either it wont work. there is no error handler for it. Just noting that you should do this to prevent this.

**Comment by NielsPilgaard** [comment]
Ah cool :P glad you figured it out!

**Comment by NielsPilgaard** [comment]
@iInjection Sorry for the ping, but would you mind making a PR that runs the ` sed -i -e 's/\r$//' *.sh` fix please? The file is still messed up whenever I do it ^^'

**Comment by iInjection** [comment]
> 
> 
> @iInjection Sorry for the ping, but would you mind making a PR that runs the ` sed -i -e 's/\r$//' *.sh` fix please? The file is still messed up whenever I do it ^^'

Sure, my Server is running fine so far

**Comment by iInjection** [comment]
Since I am a total noob whe  it comes to github, idk how to make a pull request haha but here is the file
[server-start.zip](https://github.com/NillerMedDild/Enigmatica4/files/4400120/server-start.zip)

**Comment by NielsPilgaard** [comment]
It breaks when I commit it, that's the issue :( thanks anyway!
