### ISSUE TITLE
RS Dupe Bug

### ISSUE THREAD

**Issue by XxPowerEyexX** [NillerMedDild/Enigmatica4#313]
**Modpack version**
0.4.10
**Issue**
I was playing and i noticed i couldn't shift click into the crafting grid anymore, sorta. When i try and shift click into the grid it adds it to the grid but keeps it in my inventory. ;) I recorded it just in case i didnt explain it very well.
https://youtu.be/HUbASHC7JRg

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Darkere** [comment]
Does this happen consistently to you? I've heard this once before but for them, it stopped working after a bit.
Are you in singleplayer or on a server?

**Comment by XxPowerEyexX** [comment]
single player, and i haven't restarted it but its consistent as of this play session so far

**Comment by Darkere** [comment]
Hmm ok. Please try re-entering the world/restarting the game. If the issue persists It would be great if you could upload the world. Tracking this issue down is difficult.

**Comment by XxPowerEyexX** [comment]
i restarted my game and it seems to have gone away, i will keep my eye out for it though
