### ISSUE TITLE
Iron Plates

### ISSUE THREAD

**Issue by XxPowerEyexX** [NillerMedDild/Enigmatica4#314]
**Modpack version**
0.4.10

**Issue**
iron plates in Engineers Decor are coming up with empty tag: forge:plates/iron
**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
Iron Plates are no longer available from Engineer's Decor, I suspect it's cause I added Immersive Engineering, so... fixed? :P
