### ISSUE TITLE
Ore Excavation not working

### ISSUE THREAD

**Issue by weaponsmith777** [NillerMedDild/Enigmatica4#320]
**Modpack version**
0.4.10

**Issue**
My OreExcavation is not working at all and I can not configure It to get it working, this is probably me not knowing how to use it but idk, its just not working

**Logs**
there are none of these, sorry bros

**Comment by NielsPilgaard** [comment]
Ore excavation only works on ores in E4 :)

**Comment by weaponsmith777** [comment]
Ohhhh thank you

**Comment by simonboasaeter** [comment]
You can also tweak the settings to make it work on logs :) Make sure you keybind it too
