### ISSUE TITLE
Rubber saplings

### ISSUE THREAD

**Issue by mathgirl1989** [NillerMedDild/Enigmatica4#321]
**Modpack version**
0.4.5

**Issue**
Rubber saplings do not seem to spawn in any biome. When cheated in rubber saplings grow into oak trees and drop oak tree saplings/logs. No way to get rubber to complete recipes for mods that require it.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Darkere** [comment]
Which mod requires rubber?

**Comment by mathgirl1989** [comment]
Industrial Foregoing can use it to make plastic.

**Comment by Darkere** [comment]
Industrial Foregoing Plastic is obtained by using a Fluid Extractor to create Latex, then process that in the Latex Processing machine with water into tiny dry rubber. Then craft that into plastic. 

The rubber sapling is from Blue Power and completely unrelated.

**Comment by mathgirl1989** [comment]
Ahhh, Thank you! Last time I played with that mod was quite literally called a "tree fluid extractor". Name change threw me for a loop. Well that fixes my plastic generation issue.

That being said if anyone needs rubber for Blue Power, the issue of the rubber saplings still stands.

**Comment by NielsPilgaard** [comment]
We'll look into the Blue Power issue, thanks :)

**Comment by NielsPilgaard** [comment]
https://github.com/Qmunity/BluePower/issues/466 Seems it's still work in progress.
