### ISSUE TITLE
Immersive Engineering

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica4#323]

**Comment by Discomanco** [comment]
Immersive hype!

**Comment by simonboasaeter** [comment]
awesome!

**Comment by Frogwisard1984** [comment]
just updated to newset enigmatica 4 version and immersive engineering is crashing my game
https://gist.github.com/Frogwisard1984/b1208f146bf93c1cb042be9d2fcb5589
