### ISSUE TITLE
Missing sponges

### ISSUE THREAD

**Issue by PhillishX** [NillerMedDild/Enigmatica4#324]
Enigmatica 4.10
Between 2 worlds generated I have not found a single sponge room in 4 Ocean Monuments. Is this a bug or an edit from a mod?
Is there an alternative to sponges from a Mod?

**Comment by PhillishX** [comment]
Or am I just incredibly unlucky.

**Comment by NielsPilgaard** [comment]
You're just unlucky :P I don't think we have any alternatives yet I'm afraid.

**Comment by PhillishX** [comment]
Thank you for the prompt update!
