### ISSUE TITLE
Minecolonies mod issue

### ISSUE THREAD

**Issue by simonboasaeter** [NillerMedDild/Enigmatica4#325]
**Modpack version**
0.4.10

**Issue**
Items doesnt register always when I give my bots their needed item, I go into Requests and give them their needed item with the button. However they dont notice everytime and require me to give the same amount again. I either have to go into their inventory to drag it out and give it again or bypass by go into their inventory and give them their items there instead of using the button inside Request.

**Comment by NielsPilgaard** [comment]
Possibly stupid question, but have you tried waiting? I'm thinking they might only check occasionally to produce as little lag as possible.

**Comment by simonboasaeter** [comment]
No questions are stupid! And yes, I have tried that too.

**Comment by NielsPilgaard** [comment]
Alright then, would you mind updating Minecolonies and Structurize and see if the issue persists? :)

**Comment by simonboasaeter** [comment]
Sorry if I am just unaware, but I couldnt find any newer versions for Minecraft 1.14.4.
I am running Minecolonies version 0.10.715-RELEASE and Structurize version 0.10.245-ALPHA

**Comment by NielsPilgaard** [comment]
There are more recent versions here:
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/2904832
https://www.curseforge.com/minecraft/mc-mods/structurize/files/2905203

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/2904832">Attention Required! | Cloudflare</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/structurize/files/2905203">Attention Required! | Cloudflare</a></strong></div></blockquote>

**Comment by NielsPilgaard** [comment]
Why did you close the issue?

**Comment by simonboasaeter** [comment]
Because I thought it fixed itself but it didnt :')) So the newer versions work for 1.14 too? Even though its made for 1.15?

**Comment by NielsPilgaard** [comment]
No, they don't, I just forgot this wasn't Enigmatica 5 :P sorry about that.

**Comment by NielsPilgaard** [comment]
Would you mind filling out a bug report here? https://github.com/ldtteam/minecolonies/issues/new
I have a feeling they're going to need additional details, if they support 1.14 anyhow.

<blockquote><img src="https://github.githubassets.com/images/modules/open_graph/github-logo.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 40 million people use GitHub to discover, fork, and contribute to over 100 million projects.</div></blockquote>

**Comment by simonboasaeter** [comment]
Yeah sure, I'll do that 💃 Shall I close this thread or let it stay open?

**Comment by NielsPilgaard** [comment]
Please leave it open :)
