### ISSUE TITLE
Typo in Enigmatica4Server-0.4.10 server-start.sh

### ISSUE THREAD

**Issue by nikitenok9** [NillerMedDild/Enigmatica4#327]
**Modpack version**
0.4.10 Server

**Issue**
server-start.sh file refers to "settings_linux.cfg" at line 211, whereas the server installs a "settings-linux.cfg" by default resulting in the script failing to set the variables. The forge install on linux fails due to the blank MCVER and FORGEVER settings.

**Logs**

```
INFO: Starting script at 2020-03-26_00:58:38
DEBUG: Dumping starting variables: 
DEBUG: MAX_RAM=
DEBUG: JAVA_ARGS=
DEBUG: CRASH_COUNT=
DEBUG: RUN_FROM_BAD_FOLDER=
DEBUG: IGNORE_OFFLINE=
DEBUG: MCVER=
DEBUG: FORGEVER=
DEBUG: FORGEURL=
DEBUG: Basic System Info:  Linux ubuntu-8gb-nbg1-1 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
DEBUG: Total RAM estimate:  7786.82 MB
DEBUG: Java Version info: 
DEBUG: Dumping current directory listing
```

**Comment by NielsPilgaard** [comment]
Fixed, thanks for the report :)

**Comment by NillerMedDild** [comment]
It would take longer to merge develop into master than that, fixed :)

**Comment by NielsPilgaard** [comment]
Reopened as the fix has not been released yet.
