### ISSUE TITLE
random crashes while exploring

### ISSUE THREAD

**Issue by rhaejr** [NillerMedDild/Enigmatica4#33]
**Modpack version**
0.1.3 

**Issue**
Randomly crash during exploration. Little to no problems when I am just hanging around my Minecolony.

**Logs**
https://pastebin.com/CJnzGLYR

**Comment by ArbitraryHubris** [comment]
#34 is from the same server and on the same crashlog - I'll close the other.

**Comment by NielsPilgaard** [comment]
Thank you for the report, I've reported it to the author :)

**Comment by NielsPilgaard** [comment]
https://www.curseforge.com/minecraft/mc-mods/skeleton-horse-spawn/issues/1

We should be getting a fix soon :)

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/skeleton-horse-spawn/issues/1">Access denied | www.curseforge.com used Cloudflare to restrict access</a></strong></div></blockquote>

Edit: Jesus christ Curseforge, relax.
