### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by simonboasaeter** [NillerMedDild/Enigmatica4#330]
**Modpack version**
0.5.0

**Issue**
After updating to 0.5.0 my client crashes when I join a server. Tried on a fresh world and the one I am currently playing on, same issue.

**Logs**
https://pastebin.com/i8a0F4ey

**Comment by Darkere** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/3678

**Comment by simonboasaeter** [comment]
Thanks
