### ISSUE TITLE
Disappearing items when using "simply backpacks" mod

### ISSUE THREAD

**Issue by VIcticious** [NillerMedDild/Enigmatica4#333]
**Modpack version**
0.4.5
**Issue**
Same as title, Items are disappearing when placing items into a Backpack from the Mod -Simply backpacks- 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
Known and fixed, update the modpack.
