### ISSUE TITLE
Broken Linux Launch Script 

### ISSUE THREAD

**Issue by ghost** [NillerMedDild/Enigmatica4#336]
**Modpack version**
5.1.0

**Issue**
Linux launch script for servers is non functional.

**Logs**
Not applicable.

**Comment by NielsPilgaard** [comment]
I'll find the fix for you asap :)

**Comment by NielsPilgaard** [comment]
~~Running this on the `server-start.sh` file should fix the issue: ` sed -i -e 's/\r$//' *.sh`~~ It doesn't.

**Comment by NielsPilgaard** [comment]
At long last, I found the issue, will hotfix immediately.

**Comment by NielsPilgaard** [comment]
Here's the fixed server files: https://www.curseforge.com/minecraft/modpacks/enigmatica4/files/2916688
Please let me know if they also work for you.

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/modpacks/enigmatica4/files/2916688">Attention Required! | Cloudflare</a></strong></div></blockquote>

**Comment by ghost** [comment]
That link goes nowhere.

**Comment by NielsPilgaard** [comment]
Oh right, the files haven't been approved yet, didn't expect you to answer so quickly :P Sorry! will post when they're approved

**Comment by ghost** [comment]
Yeah my average response time is like 20 min. Sorry about that :P.

**Comment by NielsPilgaard** [comment]
Haha :D the link works now.
