### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by simonboasaeter** [NillerMedDild/Enigmatica4#337]
I would like to suggest a mod for the modpack. 
Not enough wands
https://www.curseforge.com/minecraft/mc-mods/not-enough-wands

Really neat to have, especially the building wand!

**Comment by Darkere** [comment]
The 1.14 versions of not enough wands are for Fabric.

Use Building gadgets for that.

**Comment by simonboasaeter** [comment]
Ohhh, I didnt know of it. Thanks!
