### ISSUE TITLE
Unsound shell script

### ISSUE THREAD

**Issue by MagicRB** [NillerMedDild/Enigmatica4#339]
**Modpack version**
0.5.1

**Issue**
The launch script requires bash and interactive mode (the interactive mode is optional, but if you cannot get access to interactive mode, it's impossible to install the server without editing the script)

I will write a PR, if this is something you want to fix

**Comment by NielsPilgaard** [comment]
By interactive mode, do you mean it requires user input in the beginning?
That depends on how you would fix it to be honest - If you can make it work both with and without bash that would be nice, if there are no downsides.

And thank you for the offer and swift bug report :)

**Comment by MagicRB** [comment]
I'll look into it tommorow, in other words in about 12 hours

**Comment by NielsPilgaard** [comment]
Thanks, I'll answer tomorrow evening, in about 20 hours :D
