### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by simonboasaeter** [NillerMedDild/Enigmatica4#341]
I would like to suggest these two mods.
**ProjectE**
_https://www.curseforge.com/minecraft/mc-mods/projecte_

**Mystical Agradditions**
_https://www.curseforge.com/minecraft/mc-mods/mystical-agradditions_

**Comment by NielsPilgaard** [comment]
Thank you for the suggestions, however I do not think either of those mods have any place in a kitchen sink pack, as they in my opinion ruin the balance of other mods.

I'm guessing you meant Mystical Agriculture :)
