### ISSUE TITLE
Tubes Reloaded

### ISSUE THREAD

**Issue by simonboasaeter** [NillerMedDild/Enigmatica4#342]
Title explains. I havent found any easy item transporting hence why I would like to suggest this one. I hope you dont mind my suggestions :)

Tubes reloaded
https://www.curseforge.com/minecraft/mc-mods/tubes-reloaded

**Comment by NielsPilgaard** [comment]
I'll think about it, E4 does have XNet though.

**Comment by simonboasaeter** [comment]
Thanks for considering it! May I present my key points in why Tubes would be beneficial?

First of all, they dont use power to work. Item transfer requiring power in order to work will simply just hinder creativity and design. 

It's nice to look at, who doesnt love a proper automated setup with visible item transferring. I havent tried it so I dont know about FPS issues of course, but imo its worth a shot.

My third and last opinion, its way easier to use. Xnet is hard to get going and there are better, simpler ways to get started. It works for a wider amount of players.

**Comment by NielsPilgaard** [comment]
Good points, the chance of me adding it is pretty high now :)

**Comment by simonboasaeter** [comment]
Awesome!! 👯‍♂

**Comment by NielsPilgaard** [comment]
They don't really offer much as far as I can see. Inspirations pipes work pretty much the same way.
