### ISSUE TITLE
Can't apply apotheosis enchantments to tetra tools

### ISSUE THREAD

**Issue by Cyakat** [NillerMedDild/Enigmatica4#345]
**Modpack version**
0.4.10

**Issue**
I can't put apotheosis enchants on my tetra tools. I can make the apotheosis book but when I put it in the workbench it bugs out and it says how much magic it will take up and it will say how much experience it will cost but the craft button is grayed out. I assume this to be a compatibility issue.

**Logs**
N/A

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
I need to request compat from Tetra's side :)

**Comment by NielsPilgaard** [comment]
https://github.com/mickelus/tetra/issues/145
