### ISSUE TITLE
Rats features missing or non functional

### ISSUE THREAD

**Issue by zaaaaaaaaaac** [NillerMedDild/Enigmatica4#346]
**Modpack version**
0.5.1 Alpha

**Issue**
Ore doubling no functional. Rat can pick up ore block but will not consume, NEI only shows a single type (silver) of the nugget droppings.

Milking non functional. Rat will appear to hold bucket but will not milk cows.

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
https://github.com/Alex-the-666/Rats/issues/224
https://github.com/Alex-the-666/Rats/issues/225
