### ISSUE TITLE
Unable to repair tetra tools at the tetra workbench

### ISSUE THREAD

**Issue by Jesienny** [NillerMedDild/Enigmatica4#347]
**Modpack version**
0.4.10

**Issue**
Unable to repair tetra tools at the tetra workbench...but only sometimes?
I am pretty new to Tetra and Enigmatica and all those things, so i might just be doing something wrong. But since it didnt work the first day, then worked fine one day and then stopped working a day later, even though i felt like i did the same exact thing, imma try putting this here.

![image](https://user-images.githubusercontent.com/63157307/78454487-8bc0db00-7698-11ea-9271-0e8802c3feff.png)

![image](https://user-images.githubusercontent.com/63157307/78454479-7ea3ec00-7698-11ea-8a08-a60b55ffe202.png)

Wenn putting a broken Tetra tool into the workbench to try and repair it no material for repair gets recommended and dragging the repair materials of every part into the slot doesnt enable the repair either.
All parts of the tool show up as "no repair available" when examined, even though the tool is fully broken.
![image](https://user-images.githubusercontent.com/63157307/78454757-587f4b80-769a-11ea-944b-db2ff94c7132.png)

Not fully broken tools can not be repaired either.

![image](https://user-images.githubusercontent.com/63157307/78454537-de9a9280-7698-11ea-8a36-4d7bc00e015a.png)

The hammer requirement is always shown as: Hammer required: 0 Hammer available: 0
even if a higher tier hammer is in inventory.

![image](https://user-images.githubusercontent.com/63157307/78454544-e78b6400-7698-11ea-8812-cf26b5407be1.png)

The whole thing happened on a server, in case that helps.

<details>
  <summary>more pictures</summary>
  
![image](https://user-images.githubusercontent.com/63157307/78454615-6f716e00-7699-11ea-8869-2ea7a81b04fb.png)
![image](https://user-images.githubusercontent.com/63157307/78454620-76987c00-7699-11ea-8a4b-90b5db257c98.png)
![image](https://user-images.githubusercontent.com/63157307/78454629-7e582080-7699-11ea-8a6c-706667c90fa4.png)
![image](https://user-images.githubusercontent.com/63157307/78454643-b0698280-7699-11ea-943b-63f893de2441.png)
![image](https://user-images.githubusercontent.com/63157307/78454656-bfe8cb80-7699-11ea-8308-522f4a2ad847.png)
![image](https://user-images.githubusercontent.com/63157307/78454663-c8d99d00-7699-11ea-94e7-f1906cb9eaa1.png)
![image](https://user-images.githubusercontent.com/63157307/78454676-d727b900-7699-11ea-9f44-21fbf5d80728.png)

</details>

 I hope this helps.
I could not yet find a solution or workaround myself.

**Comment by NielsPilgaard** [comment]
You had a hammer in your inventory every time you tried right? :)

**Comment by Jesienny** [comment]
Yupp. You can see it in one of the pictures. I have tried two different hammers, both level 1, which worked the one time it worked and now doesnt work anymore. Same hammer, same tools, same toolstation.

**Comment by NielsPilgaard** [comment]
Aha! This has been fixed recently: https://www.curseforge.com/minecraft/mc-mods/tetra/files/2901322

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/tetra/files/2901322">Attention Required! | Cloudflare</a></strong></div></blockquote>

**Comment by NielsPilgaard** [comment]
It has been fixed in the latest modpack version :)

**Comment by Jesienny** [comment]
Ah, sorry for wasting your time then!
Couldnt find it by myself, so i thought it might have been something new.
Have a good day!

**Comment by NielsPilgaard** [comment]
You too :) It's not safe to update your server to one of the alpha versions though, I might add.
