### ISSUE TITLE
Server crashes immediately after loading

### ISSUE THREAD

**Issue by bessiq** [NillerMedDild/Enigmatica4#348]
**Modpack version**
0.5.1

**Issue**
I recently updated my E4 Linux server from 0.4.10 to 0.5.1. The server updated successfully and starts up, then crashes with a "Ticking block entity" error. This is using the provided Linux startup script, and a more generic startup script that simply has all the java arguments included. (I think both scripts are fine though.)

The error appears to have something to do with ClickMachine. I do have several of the auto-click machines in use, and they are also in chunks loaded with Persistent Bits chunk loaders. I'm just not really sure what to do to fix the issue, so I thought I'd ask an expert. :)

Any suggestions would be welcome, even if I have to do something drastic. Or destructive. Thanks!

**Logs**
Server logs
[latest.log](https://github.com/NillerMedDild/Enigmatica4/files/4434356/latest.log)
[debug.log](https://github.com/NillerMedDild/Enigmatica4/files/4434358/debug.log)
Crash log when using your provided startup script: 
[crash-2020-04-05_12.12.33-server.txt](https://github.com/NillerMedDild/Enigmatica4/files/4434368/crash-2020-04-05_12.12.33-server.txt)
Crash log when using my own script: 
[crash-2020-04-05_12.22.24-server.txt](https://github.com/NillerMedDild/Enigmatica4/files/4434357/crash-2020-04-05_12.22.24-server.txt)

**Comment by Darkere** [comment]
Your click machine is right-clicking a rat. Which causes that to try and open its inventory.
Options: 
- If you know where the click machine is you could go in with NBT explorer and remove the rat
- load the server without click machine once
- load the server without rats once

**Comment by NielsPilgaard** [comment]
~~I suspect you will need to remove all Click Machines, and even then I cannot guarantee that it'll work, the 0.5.x versions of E4 have a lot of changes.~~ Listen to Darkere :P
