### ISSUE TITLE
Veinminer (Ore Excavator) Not Working

### ISSUE THREAD

**Issue by Osprey4444** [NillerMedDild/Enigmatica4#349]
**Modpack version**
0.5.1

**Issue**
Veinminer (Ore Excavator) Not Working. I'm not too sure if you require the enchantment from Cyclic or not.

**Logs**
No Logs

**Comment by simonboasaeter** [comment]
Are you using the keybinding?

**Comment by simonboasaeter** [comment]
If you are, I also had issues earlier. Try to stop the server, delete the config files for ore excavator then start it up again. Worked like a charm after that in my case.

**Comment by NielsPilgaard** [comment]
It only works on ores :)
