### ISSUE TITLE
Exception in server tick loop - error message when I stop the server

### ISSUE THREAD

**Issue by simonboasaeter** [NillerMedDild/Enigmatica4#350]
**Modpack version**
0.5.1

**Issue**
Error as I turn off the server, didnt happen for me with version 0.4.10

**Logs**
https://pastebin.com/UJHZQawW

**Comment by NielsPilgaard** [comment]
Thanks for the report, could you please supply your server's debug.log and latest.log? I'm afraid that log isn't very helpful :(

**Comment by simonboasaeter** [comment]
[debug.log](https://github.com/NillerMedDild/Enigmatica4/files/4439264/debug.log)
[latest.log](https://github.com/NillerMedDild/Enigmatica4/files/4439270/latest.log)

Hopefully this will be more helpful then :D :D

**Comment by NielsPilgaard** [comment]
I'm afraid not, those logs don't even contain the server shutting down ><

**Comment by NielsPilgaard** [comment]
Try a new pair? :P
