### ISSUE TITLE
Failed to Synchronize Registry Data From Server, Closing Connection

### ISSUE THREAD

**Issue by Healathan** [NillerMedDild/Enigmatica4#351]
**Version**
4.5

**Issue**
I am trying to access my friends Enigmatica 4 world but everytime I do I get the failed to synchronize registry data from server, closing connection. I feel like I've tried everything to fix it, in the client log below it shows the error has something to do with KubeJS. I have tried replacing that file with the servers kubejs files, tried every possible launcher and installer and replaced my geolysis.json files.My friend has restarted the server. And I still get the same error message because my Mac refuses to install one part of a mod. Please any help would be appreciated.

**Log**
https://pastebin.com/X2VR654r

**Comment by NielsPilgaard** [comment]
Either you or the server is missing the KubeJS folder :)
