### ISSUE TITLE
Putting Liquid in Buckets with Machine

### ISSUE THREAD

**Issue by Cyakat** [NillerMedDild/Enigmatica4#352]
**Modpack version**
0.4.10

**Issue**
I don't know if there is a way in future versions but it would be nice to be able to put liquids in buckets with a machine because it would be nice for refined storage autocrafting.

**Logs**
N/A

**Comment by NielsPilgaard** [comment]
We'll get one eventually as mods update, I don't think there are any available at the moment :)

**Comment by Darkere** [comment]
That machine can be the vanilla dispenser ;)

You can also (ab)use the silents mechanisms pump for this

**Comment by NielsPilgaard** [comment]
Good point :D

**Comment by Cyakat** [comment]
I figured out I can just use modular routers with the fluid module for this. This is so anyone else who is wondering can view this thread.
