### ISSUE TITLE
[Mod Suggestion] Name Pain

### ISSUE THREAD

**Issue by naqaden** [NillerMedDild/Enigmatica4#353]
[Name Pain](https://www.curseforge.com/minecraft/mc-mods/name-pain) is a light client-side QoL/tweak mod for vanilla nameplates. Since Neat is already in this pack, NP's primary function of visualizing health is redundant. I'm suggesting it instead for its ability to hide vanilla nameplates as Neat already displays names. Alternatively it could be used to just customize vanilla nameplates via RGBA configs for looks.

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion, I'll try it out :)

**Comment by NielsPilgaard** [comment]
Actually I want to keep vanilla nameplates, as their range is higher than that of NEAT. I appreciate the suggestion, but at this time it's a no thank you :)
