### ISSUE TITLE
Copper Ore from Create spawning

### ISSUE THREAD

**Issue by elko81** [NillerMedDild/Enigmatica4#354]
**Modpack version**
0.5.1

**Issue**
The silent's mechanisms copper ore looks like the only one that can be processed - other mod variants don't have any processing recipes at all according to JEI, and i've tried them in the Create millstone and crushing wheel with no result. There's also no recipe to convert the ore types manually like there is with zinc ore for example.

**Comment by NielsPilgaard** [comment]
Thanks for the report. How did you obtain the other Copper Ore variants?

**Comment by milibucket** [comment]
Just started playing. I am having the same issue here. Apparently the copper ore from Create spawns the most abundantly, I have yet to find the mechanism and other variant copper ore in the wild.

**Comment by NielsPilgaard** [comment]
Awesome, I'll get that fixed - I guess the Create config changed :)

**Comment by elko81** [comment]
I think there might be something going on with Zinc ore too - i've got both Create and Silent's zinc ore. When i was playing yesterday, i had no recipe to convert Create copper into Silent's but i did have one to convert the zinc. Logged in again today without having updated anything, and now i have a recipe to convert the copper ore but not the zinc.

**Comment by NielsPilgaard** [comment]
Yep you're correct, I also fixed that :)
I have also fixed the conversion recipes, just in case.

**Comment by elko81** [comment]
Quick question on this - the crushing wheel recipes for the copper and zinc ore from Silent's dont produce crushed ores, they produce ingots and nuggets directly. It makes sense for those ores that there's no equivalent for in Create, but it also means that the Create ore doubling via crushing & then washing doesn't apply to anything other than iron & gold anymore - it pushes you towards using the silent's machines for processing, which is a shame considering how cool Create is. Would it be possible to change those crushing wheel recipes for copper & zinc specifically (or even better if create allows for other crushed ore types to be added)?

**Comment by NielsPilgaard** [comment]
Ah, I didn't know my Create datapack broke, I'll get that fixed, thanks :)
