### ISSUE TITLE
Random Stalls/Crashes

### ISSUE THREAD

**Issue by Osprey4444** [NillerMedDild/Enigmatica4#357]
**Modpack version**
0.5.1

**Issue**
Random Stalls/Crashes

**Logs**
https://hastebin.com/ijegaqemem.rb - Crash
https://gist.github.com/Osprey4444/d161f747452a05e817610a0b46f79e54 - Latest

**Comment by NielsPilgaard** [comment]
I believe the cause is the mod `DiscordIntegration` you added - The log is filled with errors from it. I'm thinking it threw so many errors your server lagged itself to death.

**Comment by Osprey4444** [comment]
> I believe the cause is the mod `DiscordIntegration` you added - The log is filled with errors from it. I'm thinking it threw so many errors your server lagged itself to death.

It was stalling before I added DiscordIntegration, but I will remove it and continue further tests and let you know.

**Comment by NielsPilgaard** [comment]
Sounds good, please supply debug.log and latest.log when the stall comes back :)
