### ISSUE TITLE
Console Spam from various mods

### ISSUE THREAD

**Issue by Osprey4444** [NillerMedDild/Enigmatica4#358]
**Modpack version**
0.5.1

**Issue**
Various console spam saying "Cannot Serialize.

**Logs**
Latest Log - https://gist.github.com/Osprey4444/bfe346c04cbf6119321bb05b3bab7983
(Ignore the DC.integration Spam)

**Comment by NielsPilgaard** [comment]
I'm aware of the issue, and I'm afraid it won't be solved. The mod author doesn't support 1.14.4 anymore.
