### ISSUE TITLE
Disabled refined storage controller still consumes power

### ISSUE THREAD

**Issue by Cyakat** [NillerMedDild/Enigmatica4#360]
**Modpack version**
0.4.10

**Issue**
When I turn of the refined storage controller it still consumes power.

**Logs**
N/A

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Darkere** [comment]
Appears to be due to a config change you did to make controller use 1FE as Base Usage. 

Of course, that shouldn't consume power when turned off. Gonna make a report.

**Comment by Darkere** [comment]
Reported here: https://github.com/raoulvdberge/refinedstorage/issues/2478

Dev hasn't worked on RS in 3 months so it might be a bit until it's fixed.

**Comment by raoulvdberge** [comment]
Should be fixed now!
