### ISSUE TITLE
Advanced Dimensional Dungeons Portal Crashes When Used

### ISSUE THREAD

**Issue by WugWugg** [NillerMedDild/Enigmatica4#365]
**Modpack version**
Version 0.5.1

**Issue**
After constructing the advanced dimensional dungeons portal and inserting an advanced (read: green colored) key the server crashes. Upon restart the server has opened the portal but only one block is active (see picture). The portal is functional after restart and allows the player to travel to the dungeon with no further issue. Removing the key is fine also. Inserting a basic (read: tan colored) key works with no problems with this setup.

**Logs**
Crash Report:
https://pastebin.com/raw/f3tzQcYa

Portal after restart
![image](https://user-images.githubusercontent.com/4581733/79035757-7adc0200-7b8f-11ea-81d5-64debd0d760e.png)

**Comment by NielsPilgaard** [comment]
Thank you for the report, I relayed it :)
