### ISSUE TITLE
Excavation enchant empties shulkers

### ISSUE THREAD

**Issue by Nabegane** [NillerMedDild/Enigmatica4#369]
**Modpack version**
Enigmatica 4 0.5.1

**Issue**
When breaking a shulker box with a Cyclics excavation enchanted pickaxe and there is a similar colored shulker boxes right next to it the pickaxe excavates all the similar colored shulkers, drops them as items like it should but all the shulkers are empty.
If you use the enchanted pickaxe to mine only one shulker that dosent have same colored ones next to it, the shulker retains its contents. Same if there are different colored shulkers next to each other the pickaxe will only mine the one and the shulker keeps its contents.

**Comment by NielsPilgaard** [comment]
Thanks for the report, I've relayed it :)
