### ISSUE TITLE
The Midnight dimension crash on enter

### ISSUE THREAD

**Issue by fGravity** [NillerMedDild/Enigmatica4#37]
**Modpack version**
E4 0.1.3

**Issue**
Get a client crash every time when trying to go into the portal for the Midnight dimension

**Logs**
https://pastebin.com/tNUZMcrH

**Comment by NielsPilgaard** [comment]
https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/issues/94

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/issues/94">Access denied | www.curseforge.com used Cloudflare to restrict access</a></strong></div></blockquote>
