### ISSUE TITLE
Powah Energy Cell Recipe & Energy Capacity Buffs

### ISSUE THREAD

**Issue by DwellerBenthos** [NillerMedDild/Enigmatica4#370]
**Modpack version**
0.4.10

**Issue**
Higher end Powah energy cells require the lower tier cells to craft but don't hold as much power as the lower tier cells taken by themselves. A basic cell stores 100K FE. It takes four basic cells to make a hardened cell which then only holds 200K FE. You're better off just stacking the four basic cells in a chain than wasting two of them to make the next tier cell that doesn't hold as much. The higher tier cells after that work out but there's really no bonus making the larger cells except that you get the same storage capacity in a smaller space. There should at least be some bonus for making the higher tier cells to reflect the extra work and materials needed to make them. Watching Vallen's bit by bit for the mod, it looks like the default for the basic cell is a million FE so I'm guessing the values have been adjusted down for the pack. It would be better if either the recipes were also adjusted to reflect this or a different set of values used for the storage capacity that makes more sense for the materials used.

**Comment by NielsPilgaard** [comment]
Good points, I'll have another look at it :) I didn't realize each upgrade required 4 of the previous.
