### ISSUE TITLE
Vanilla recipes should accept Botania dyes

### ISSUE THREAD

**Issue by Cyakat** [NillerMedDild/Enigmatica4#371]
**Modpack version**
0.5.2

**Issue**
It would be nice if I could craft concrete blocks with floral powder as the dyes since I can do that with other blocks or if the floral powder could be crafted into dye.

**Logs**
N/A

**Comment by NielsPilgaard** [comment]
Sure thing, got a very similar issues on the E5 issue tracker.

Glass, Glass Panes, Terracotta, Concrete, Wool, Carpet
