### ISSUE TITLE
Immersive block of lead uncraftable.

### ISSUE THREAD

**Issue by ClaymooreEOC** [NillerMedDild/Enigmatica4#374]
**Modpack version**
V0,5,1

**Issue**
Immersive enginnering HV capacitor is uncraftable since it does not accept Silents lead block and immersive lead block is not craftable.

Wanted to make a railgun for the lulz. :(

**Comment by NielsPilgaard** [comment]
Thanks for the report, I'll get that fixed :)

**Comment by NielsPilgaard** [comment]
Reported here: https://github.com/BluSunrize/ImmersiveEngineering/issues/3812
will fix it myself while we wait.
