### ISSUE TITLE
Server suddenly failed to launch

### ISSUE THREAD

**Issue by TheDylanSneaker** [NillerMedDild/Enigmatica4#377]
**Modpack version**
0.4.10

**Issue**
After (doing my best to) configure, the server I made for my friends and I has started to.. stop.. launching...

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica4/files/4519071/latest.log)

**Comment by Darkere** [comment]
Gonna need this crash report
` This crash report has been saved to: D:\Games\Minecraft Stuff\ServerShat\.\crash-reports\crash-2020-04-22_23.22.17-server.txt`

Did you change any files before the last launch?

**Comment by TheDylanSneaker** [comment]
[crash-2020-04-22_23.22.17-server.txt](https://github.com/NillerMedDild/Enigmatica4/files/4519091/crash-2020-04-22_23.22.17-server.txt)

Only put in a new seed

**Comment by NielsPilgaard** [comment]
Please supply the `server.properties` file :)

**Comment by TheDylanSneaker** [comment]
![afbeelding](https://user-images.githubusercontent.com/64170065/80036392-ef992f80-84f1-11ea-86ae-0a657ea6d9a5.png)


I'm awfully well aware this isn't the.. actual file... But it kept refusing to upload, I hope this will do!

**Comment by NielsPilgaard** [comment]
Try removing the seed, and checking for random whitespaces please.

**Comment by TheDylanSneaker** [comment]
I do believe that did it, endless thanks!

I.. do have one more question, I can't seem to figure out how to increase the amount of RAM available.. 1.5GB (which I believe is default) sounds rather puny for a server even if it is for only a handful of people.

**Comment by NielsPilgaard** [comment]
Nice!

RAM is set in the `settings.cfg` file, with the `MAX_RAM` config.
