### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by Pizza678** [NillerMedDild/Enigmatica4#378]
**Modpack version**
0.54

**Issue**
Crashing while loading up

**Logs**
[crash-2020-04-23_13.21.29-client.txt](https://github.com/NillerMedDild/Enigmatica4/files/4522440/crash-2020-04-23_13.21.29-client.txt)

**Comment by Darkere** [comment]
Optifine has not been updated to work with the newest forge versions on 1.14.
