### ISSUE TITLE
0.5.3 crashing with IE belts

### ISSUE THREAD

**Issue by Pixelmnkey** [NillerMedDild/Enigmatica4#380]
**Modpack version**
0.5.3

**Issue**
Tossing items or trying to extract into IE belts causes a server crash.
**Logs**
[crash-2020-04-24_14.01.37-server.txt](https://github.com/NillerMedDild/Enigmatica4/files/4528725/crash-2020-04-24_14.01.37-server.txt)

**Comment by NielsPilgaard** [comment]
Please update to 0.5.4 and see if it persists :)

**Comment by Pixelmnkey** [comment]
I just updated server to 0.5.3 yesterday, will try to update again today and get back to you.

**Comment by Pixelmnkey** [comment]
Fixed with 0.5.4, thanks!

**Comment by NielsPilgaard** [comment]
Nice :D
