### ISSUE TITLE
0.5.3 Needs stained_glass to craft stained glass?

### ISSUE THREAD

**Issue by Pixelmnkey** [NillerMedDild/Enigmatica4#381]
**Modpack version**
0.5.3
**Issue**
Aparently you need stained glass to craft stained glass or am I missing something? Can I edit somehow the crafting recipe back to normal?

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Update to 0.5.4 :)
