### ISSUE TITLE
Please split server install out of server-start.sh 

### ISSUE THREAD

**Issue by unexceptable** [NillerMedDild/Enigmatica4#383]
**Modpack version**
0.5.4

**Issue**
I do a docker build of modpacks that I tend to run for myself and others, and I like to be able to download the server modpack, and then install it (and forge). See:
https://gitlab.com/minecraft-docker/enigmatica4

The entrypoint for the container is then the server start script, but I don't like the forge install happening every time the container starts up, and would rather have that happen only when the container is build. The container when run should just start the server with little external downloading needed, and people can mount in world/config files as needed.

If you had a `server-install.sh` script, I could call that in my build, and the container on start up would just call `server-start.sh`. You can still have the logic in `server-start.sh` call the install script to ensure Forge and Minecraft is installed. Which in my case would work fine since the start script would see Forge was already there, and do nothing other than start the server.

FTB do something similar with their modpacks, and it makes the process a little nicer:
https://gitlab.com/minecraft-docker/ftb-revelation/-/blob/latest/dockerfile#L11

**Comment by NielsPilgaard** [comment]
The `server-start.sh` doesn't download Forge or Minecraft if they're already installed, so I'm not sure what the issue is?
Edit: Really cool that you're making Docker builds for modpacks!

**Comment by unexceptable** [comment]
The problem is that I don't see a way to run the server start script without also running the server, and if I did that in the build process just to have it install forge, I couldn't then halt it. I just want to run the install forge part so it gets built into the container image, and then when someone runs the container the server/forge code is already setup.

**Comment by NielsPilgaard** [comment]
Ah alright, that's definitely do-able :)

**Comment by unexceptable** [comment]
Awesome. Ty!

**Comment by NielsPilgaard** [comment]
Do you want the server to be started once to generate the eula, in the install-server script?

**Comment by NielsPilgaard** [comment]
Would you mind checking if the file created in commit 98d940a ^ works as you would like? :)

**Comment by unexceptable** [comment]
@NillerMedDild Yep that looks good! Just haven't had a chance to test it yet, but definitely looks like it would solve my problem. :)

In my case, no need to deal with the eula, I just place a file for that, and for most that should be easy enough.
