### ISSUE TITLE
Server is coming up as incompatible (although it isn't)

### ISSUE THREAD

**Issue by unexceptable** [NillerMedDild/Enigmatica4#384]
**Modpack version**
0.5.4

**Issue**
When setting up the Modpack in either Twitch or MultiMC I have the modpack on my server coming up as incompatible despite both the server and client running the same version.

Not sure if this is due to something I've misconfigured, or something in the modpack itself.

But if you login anyway, it just works.

**Comment by Darkere** [comment]
Not your issue. One of the mods that is only clientside or only server side is missing a piece of code that makes them appear as compatible.

**Comment by NielsPilgaard** [comment]
We're working on resolving this issue, but it requires that all client side-only mods can load on a server, which isn't the case yet.
