### ISSUE TITLE
enigmatica 4 optifine dont load

### ISSUE THREAD

**Issue by StenaLeonny** [NillerMedDild/Enigmatica4#387]
the modpack dont open with optifine.

**Comment by StenaLeonny** [comment]
I play other 1.14.4 modpack. And optifine works. Perfectly

**Comment by StenaLeonny** [comment]
But in enigmática  4 modpack crash before main menu.

**Comment by NielsPilgaard** [comment]
Please don't open duplicate issues, just comment on the old one.
