### ISSUE TITLE
Very easy item duping

### ISSUE THREAD

**Issue by DylanMcBean** [NillerMedDild/Enigmatica4#390]
**Modpack version**
ENIGMATICA 4

**Issue**
very easy item dupping (tetra + mouse tweaks)

**Video**
https://streamable.com/jpfxx5

**Comment by NielsPilgaard** [comment]
Enigmatica 4 isn't a modpack version, which version did this occur in?

**Comment by mickelus** [comment]
I'm unable to reproduce this with just tetra and mouse tweaks, have not tested in e4 yet. What is mouse tweaks supposed to do when you middleclick?

tetra 1.14.4-1.27.0
mouse tweaks 2.13-mc1.14.4
forge 28.2.6

**Comment by Darkere** [comment]
MouseTweaks doesn't add any sorting functionality. Would need to be Inventory Sorter or Inventory Tweaks Reborn. Hence, the question about which exact version. Inventory tweaks was removed in a recent version.
