### ISSUE TITLE
Cursed earth not working; nothing spawning in SP or MP

### ISSUE THREAD

**Issue by s3717566** [NillerMedDild/Enigmatica4#392]
**Modpack version**
0.5.4

**Issue**
Cursed earth does not spawn any mobs. Complete darkness, testing on multiplayer and single player. Appears to be a common issue from the enigmatica 4 discord. The cursed earth spreads fine, but nothing spawns.

**Logs**

**Comment by NielsPilgaard** [comment]
May I have a screenshot of the setup please?

**Comment by s3717566** [comment]
Sure, here are some discord comments on it just to make sure that is definitely isn't just me first lol
![image](https://user-images.githubusercontent.com/41351637/80774931-99875480-8ba1-11ea-8f5a-779a6f9892f7.png)
![image](https://user-images.githubusercontent.com/41351637/80774991-c20f4e80-8ba1-11ea-9faa-f708b57f13ed.png)



Here's my setup
![2020-05-01_11 43 15](https://user-images.githubusercontent.com/41351637/80774778-457c7000-8ba1-11ea-9350-ada323bf953c.png)
![2020-05-01_11 42 56](https://user-images.githubusercontent.com/41351637/80774783-47deca00-8ba1-11ea-95c5-32d26ed7e7c9.png)

Thanks!

**Comment by NielsPilgaard** [comment]
Thanks, I'll investigate.

**Comment by NielsPilgaard** [comment]
I done messed up, it's configured to stop if there are more than 25 hostile mobs in the world.
