### ISSUE TITLE
IE/JEI 

### ISSUE THREAD

**Issue by StalkerM8** [NillerMedDild/Enigmatica4#395]
**Modpack version**
Latest release

**Issue**
Within the various Immersive Engineering structures (Ex. Alloy Kiln) the "Show Recipes" doesn't do anything. JEI doesn't show the IE recipes from these structures either. This is on a server if that matters. The world was generated in the older version too if that counts.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Which modpack version are you using? Latest isn't helpful at all.

**Comment by StalkerM8** [comment]
Which ever is the Latest RELEASE, I can't check from MultiMC

**Comment by NielsPilgaard** [comment]
Multiblock recipes are being re-made in the next update of IE, I hope this will be resolved then.

**Comment by StalkerM8** [comment]
Thanks we'll see

**Comment by NielsPilgaard** [comment]
It was indeed fixed in their update.
