### ISSUE TITLE
[0.5.4] Ie Blueprints missing?

### ISSUE THREAD

**Issue by Pixelmnkey** [NillerMedDild/Enigmatica4#396]
**Modpack version**
0.5.4

**Issue**
I had IE blueprints on my engineers table and now they're just generic blueprints with no attributes, upon looking JEI they're not there anymore, is it intentional? Do we need to find 'em on villages or its a real issue?

Sorry if' that has been posted before, didn't see it.

Thanks!

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Will be fixed in next update of IE, thank you for the report :)
https://github.com/BluSunrize/ImmersiveEngineering/issues/3833

**Comment by Pixelmnkey** [comment]
Cool! Thanks man, one of the bests modpacks, thanks for your dedication :+1:
