### ISSUE TITLE
Create copper ore recipe Issue

### ISSUE THREAD

**Issue by Drackion** [NillerMedDild/Enigmatica4#397]
**Modpack version**
0.5.4

**Issue**
Create copper ore is no longer converting into silent mechanism's copper ore when placed in the crafting table. The uses of the Create copper ore show it can only but used in the Immersive Engineering Crusher and Arc Furnace.
![Create copper ore error](https://user-images.githubusercontent.com/64641342/80858119-8e641f80-8c9a-11ea-928b-6922cc526c8a.png)
 

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Did you modify the pack in any way? If no, please reinstall it and let me know if that is still an issue.

**Comment by Drackion** [comment]
Slight modifications Mods add: Pickle Tweaks, Stone chests, better barrels, metal barrels and iron shulkers. but with these mods it recipe worked when i first updated to 0.5.4 but disappeared the next day and just in case have tried a fresh install and still the recipe is missing.

**Comment by NielsPilgaard** [comment]
Alright, I'll try to reproduce it, thanks.

**Comment by NielsPilgaard** [comment]
Still works just fine for me :/
![billede](https://user-images.githubusercontent.com/21295394/80860241-b6399000-8c66-11ea-9500-9419eb4f4b40.png)
