### ISSUE TITLE
Cannot Shift Click Out of Resourceful Furnace from Industrial foregoing 

### ISSUE THREAD

**Issue by Blizhazard** [NillerMedDild/Enigmatica4#399]
**Modpack version**
0.5.4

**Issue**
Shift-Clicking a finished product in an industrial foregoing resourceful furnace doesn't do anything when it should go into your inventory.

**Logs**
N/A

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
Confirmed the issue, but I do not think the mod author supports 1.14 anymore, so this will most likely not be fixed.
