### ISSUE TITLE
Traverse's Fir Logs cannot be stripped

### ISSUE THREAD

**Issue by SuiguraTaiki** [NillerMedDild/Enigmatica4#400]
**Modpack version**
Fresh Enigmatica 4 0.5.4

**Issue**
Traverse's Fir Logs cannot be stripped through any modded or not axe, nor is there a crafting option to do so.

**Suggestion**
Add a recipe to make use of the Corail Sawmill to be able to craft stripped logs, in case this cannot be fixed. If possible, do this to all logs.

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.
