### ISSUE TITLE
Almost no way to make the Immersive Engineering Steel Block

### ISSUE THREAD

**Issue by cphase** [NillerMedDild/Enigmatica4#401]
**Modpack version**
0.5.4

**Issue**
The recipe to make a steel block only will make the silent's version, even when using immersive engineering steel block. Even using the 3x3 packing mold on the metal press makes the wrong version. the only way i can find to specifically make the Immersive Engineering Steel Block (which I needed for the excavator multiblock) was to use iron blocks in the blast furnace, which took forever. In other modpacks I've seen a little arrow for crafting different items with the same recipe, wonder if that would work here.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Ah I didn't think of that, I'll add a special recipe for it, thanks for the report. This will eventually be fixed by Chisel, if it ever becomes available for 1.14.4 that is.
