### ISSUE TITLE
Simply Backpacks deleting items

### ISSUE THREAD

**Issue by sportsziggy** [NillerMedDild/Enigmatica4#402]
**Modpack version**
v.0.5.4

**Issue**
Items are getting deleted out of Simply Backpack's backpacks.
Similar to [this](https://github.com/NillerMedDild/Enigmatica4/issues/282) and [this](https://github.com/NillerMedDild/Enigmatica4/issues/333) in the past.

**Logs**
[Youtube video showcasing](https://youtu.be/W2HmRI_iy9Q)

**Comment by NielsPilgaard** [comment]
Thanks for the report, I'll look into it again ^^

**Comment by sportsziggy** [comment]
> 
> 
> Thanks for the report, I'll look into it again ^^

Thanks. Didn't see anything on SimplyBackpacks github. I was able to recreate it.

**Comment by NielsPilgaard** [comment]
I was unable to reproduce this issue, would you mind trying again in 0.5.5 once I release it? :)
