### ISSUE TITLE
Crash on startup client and server

### ISSUE THREAD

**Issue by Justin-J-Morgan** [NillerMedDild/Enigmatica4#403]
**Modpack version**
0.5.4

**Issue**
doesn't even get to forge mod loader screen. tried ram from 3 to 16 gigs, no difference

**Logs**
https://pastebin.com/ATuXBc4r

**Comment by NielsPilgaard** [comment]
Have a look at this #281 :)
Twitch has failed to download some part of Forge or Minecraft.
