### ISSUE TITLE
Ticking Memory Connection when trying to load up or create a new world.

### ISSUE THREAD

**Issue by Legatonin** [NillerMedDild/Enigmatica4#405]
**Modpack version**
Version 0.5.4

**Issue**
Couldn't load the map due to Ticking memory connection

**Logs**
https://pastebin.com/yiB6ePae

**Comment by NielsPilgaard** [comment]
Thanks for the report - Could you please try to reinstall the pack? :)

**Comment by Legatonin** [comment]
> Thanks for the report - Could you please try to reinstall the pack? :)

I knew that would do it.

I got it working again with reinstalling the whole pack.

Thanks.

**Comment by NielsPilgaard** [comment]
Awesome :D feel free to comment here if you come across the issue again.
