### ISSUE TITLE
Launching vanilla 1.14.4 instead of modpack

### ISSUE THREAD

**Issue by Duelwings** [NillerMedDild/Enigmatica4#407]
**Modpack version**
Version: 0.5.4
Minecraft Version: 1.14.4
(modded) forge-28.2.4

**Issue**
When launching after a few seconds the "FML early loading progress" just opens another window that is just vanilla 1.14.4 and then idles just saying memory heap and offheap.

Tried reinstalling and changing modloader and version number and changing it back, same problem regardless.

**Comment by NielsPilgaard** [comment]
This isn't an issue with the modpack, it's most likely caused by the launcher you're using (I'm guessing Twitch) or something went wrong with the install. I'm gonna give you a link to the Discord server for support below.
