### ISSUE TITLE
Incompatibility with Optiforge?

### ISSUE THREAD

**Issue by Redcom1988** [NillerMedDild/Enigmatica4#408]
Enigmatica 0.5.4

It seems that when the mod "Optiforge" and it's dependencies are installed, after a few minutes loaded into a world the creative icons become blank, and the display name of items turn into []][[[]]]

I could attach a screenshot if needed

**Comment by Redcom1988** [comment]
Sorry about that, just found out that optifine overall is just incompatible with immersive engineering

**Comment by NielsPilgaard** [comment]
Myeah pretty much :(
