### ISSUE TITLE
JEI and Simple Storage Network Request Table

### ISSUE THREAD

**Issue by max-m-s** [NillerMedDild/Enigmatica4#409]
**Modpack version**
 0.5.4

**Issue**
Auto filling recipes from JEI doesn't use any available material. For example any type of wood plank, unless you have the exact one displayed on the recipe at the time. Also it will not fill recipes that use an item with damage. Other crafting tables work fine. I'm not sure if this is just with SSN 1.14 (currently 1.14.4-0.2.0), it certainly had this feature in 1.12.

**Logs**
Shouldn't be necessary. Nothing is coming out when the filling the recipe fails.

**Comment by NielsPilgaard** [comment]
I think SSN is a bit on the unfinished side on 1.14 :P I'm tempted to just remove it to be honest, since we have RS anyway.

**Comment by max-m-s** [comment]
Yeah so much functionality is missing, like setting priorities and the more advanced remotes.  I'm surprised they have to start from scratch rather than porting to new Minecraft versions. Just checking it wasn't a compatibility issue. Thanks for replying.

**Comment by NielsPilgaard** [comment]
Sure thing, thanks for the report!
