### ISSUE TITLE
Weakness makes them stop damaging you

### ISSUE THREAD

**Issue by Legatonin** [NillerMedDild/Enigmatica4#417]
**Modpack version**
0.5.4

**Issue**
The Weakness effect from EverlastingAbilities mod causes melee type mobs from damaging you after one hit from them. Skeletons are fine, but only from mobs that deal melee damage.
It seems pretty god mode from this point, so i removed it from myself.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
Huh. The same applies for vanilla weakness potions, this isn't a mod issue :s
https://github.com/CyclopsMC/EverlastingAbilities/issues/120

**Comment by Darkere** [comment]
Fixed in 1.16 ;)

**Comment by NielsPilgaard** [comment]
I disabled the Weakness Everlasting Ability to "remedy" this issue.
