### ISSUE TITLE
powah hardened power cell not craft 

### ISSUE THREAD

**Issue by Gunfingerz** [NillerMedDild/Enigmatica4#418]
**Modpack version**
4

**Issue**
powah hardened power cell not craft 

![image](https://user-images.githubusercontent.com/65781891/82692951-7f98d900-9c58-11ea-8caa-7d8aeb053eb6.png)

![image](https://user-images.githubusercontent.com/65781891/82693071-be2e9380-9c58-11ea-8a97-bc4c99f536fa.png)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
Confirmed the issue, you can click the empty output to get it though.
