### ISSUE TITLE
Botania Book Recipes are messed up.

### ISSUE THREAD

**Issue by kulwych** [NillerMedDild/Enigmatica4#419]
starting the lexica botania book and i am getting to anything that requires the petal apothecary and all i see in the book are things like this. they all lead to something that makes some sort of sawmill.
https://puu.sh/FNKKJ/cfc1b75ed8.png

**Comment by kulwych** [comment]
instead of a link, heres an uploaded picture.  
![javaw_25IBLjxF0X](https://user-images.githubusercontent.com/26035070/82721319-ccdd7080-9c81-11ea-867c-8e96912b4edb.png)

**Comment by NielsPilgaard** [comment]
Duplicate of  #373

**Comment by kulwych** [comment]
ah didn't see that one sorry ab the repost then. :D
