### ISSUE TITLE
Rats & Rat Pipers not spawning

### ISSUE THREAD

**Issue by Kre4ch** [NillerMedDild/Enigmatica4#421]
**Modpack version**
0.5.4

**Issue**
No rats or pipers are spawning, with even adjusted configs in server files. Spawning rats work. Vanilla mobs are also spawning on top of garbage piles which is not supposed to happen

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
Ah yes, I should just need to update, will get it done asap:
https://github.com/Alex-the-666/Rats/issues/210
