### ISSUE TITLE
Light sources stop giving light

### ISSUE THREAD

**Issue by kailajay** [NillerMedDild/Enigmatica4#424]
**Modpack version**
0.5.5/Official server

**Issue**
Torches and other light sources reset/stop giving out light. On the main E4 server via the official discord.

![image](https://user-images.githubusercontent.com/52497374/84136335-0f08ff00-aa43-11ea-9d9d-49debe7bc574.png)

**Comment by NielsPilgaard** [comment]
Huh, that is odd. Would you mind re-taking that screenshot (or similar) with the F3 overlay on?
