### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by Booker117** [NillerMedDild/Enigmatica4#425]
**Modpack version**
Enigmatica 4, 1.14.4, 0.5.5

**Issue**
Every time i try to start the server it crash and i have tried everything, i'm not very good at java script so i'm not sure what else to try. 

**Logs**
Starting Enigmatica 4 Server...
DEBUG: Attempting to execute [ java -Xmx4G -Xms2G -d64 -server -XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:+UseAdaptiveGCBoundary -jar "C:\Users\Admin\Desktop\Enigmatica 4 Server\forge-1.14.4-28.2.16.jar" nogui ]
2020-06-11 16:13:21,059 main ERROR Error processing element Queue ([Appenders: null]): CLASS_NOT_FOUND
2020-06-11 16:13:21,105 main WARN Advanced terminal features are not available in this environment
2020-06-11 16:13:21,138 main ERROR Unable to locate appender "ServerGuiConsole" for logger config "root"
[32m[16:13:21] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 28.2.16, --fml.mcpVersion, 20190829.143755, --fml.mcVersion, 1.14.4, --fml.forgeGroup, net.minecraftforge, nogui]
[m[32m[16:13:21] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 4.1.0+62+5bfa59b starting: java version 1.8.0_251 by Oracle Corporation
[m[32m[16:13:21] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[mException in thread "main" [32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: org/apache/commons/lang3/tuple/Pair
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:184)
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:92)
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.util.HashMap$Values.forEach(Unknown Source)
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.tuple.Pair
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.net.URLClassLoader.findClass(Unknown Source)
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.ClassLoader.loadClass(Unknown Source)
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.ClassLoader.loadClass(Unknown Source)
[m[32m[16:13:21] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         ... 12 more
[m
WARN: Enigmatica 4 Server was stopped (possibly crashed)...
At 6/02:161317 Server has stopped.
Server has 1 consecutive stops, each within 600 seconds of eachother...

**Comment by NielsPilgaard** [comment]
Possibly a silly question, but have you tried reinstalling? :)

**Comment by Booker117** [comment]
Not at all a silly question, because what’s silly is that I haven’t tried
reinstalling :/
