### ISSUE TITLE
Crash on world load (v0.5.5)

### ISSUE THREAD

**Issue by mathematiqueNageur** [NillerMedDild/Enigmatica4#426]
**Modpack version**
0.5.5

**Issue**
Game crashes upon loading world. Game originally crashed when working on a Create mod conveyor system after placing a press and then adding brass supports to the conveyor. 

**Logs**
Attached(Not a pastebin pro user)
[crash-2020-06-15_03.18.05-server.txt](https://github.com/NillerMedDild/Enigmatica4/files/4778663/crash-2020-06-15_03.18.05-server.txt)

[latest.log](https://github.com/NillerMedDild/Enigmatica4/files/4778660/latest.log)

**Comment by NielsPilgaard** [comment]
Thanks for the report. I believe this issue will be resolved if you update Create, would you mind giving that a go?

**Comment by mathematiqueNageur** [comment]
To clarify, do you mean that I should replace the mod file with one from 1.15? The version in the pack is already the most up to date version for 1.14.

**Comment by NielsPilgaard** [comment]
Ah dammit, I thought we were a few updates behind on 1.14. Don't update :) 
You'll have to remove the block using something like MCEdit.

**Comment by NielsPilgaard** [comment]
I'm afraid there's not really anything we can do about it, Create has moved to 1.15 like the majority of mods in Enigmatica 4 :(
