### ISSUE TITLE
Missing Addon ID: 314911

### ISSUE THREAD

**Issue by max-m-s** [NillerMedDild/Enigmatica4#429]
**Modpack version**
v0.5.5

**Issue**
Can no longer install (update) via twitch:
"This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 314911"

Since I was doing an update, I've lost the current working version and cannot reinstall it.

**Logs**
N/A

**Comment by Darkere** [comment]
Twitch is having issues. Not something we could help with. Just try again at a later date.

(or figure out how to use the backup twitch makes)
