### ISSUE TITLE
Mouse middle-click sort doesn't work unless another inventory is open

### ISSUE THREAD

**Issue by ArbitraryHubris** [NillerMedDild/Enigmatica4#48]
**Modpack version**
0.1.3

**Issue**
If I open my player inventory and middle-click the mouse, I get no sort.   If I open a vanilla chest I can middle click in the chest inventory and sort works.  Also, I can middle-click the player inventory while the chest is open and it sorts the player inventory.  I thought this might be a conflict with ` so I remapped the only conflict and it didn't solve the issue.

**Comment by NielsPilgaard** [comment]
Thank you for the report, the issue has been reported.
