### ISSUE TITLE
Malformed JSON

### ISSUE THREAD

**Issue by janagyjr** [NillerMedDild/Enigmatica4#49]
**Modpack version**
0.1.3

**Issue**
Malformed JSON

**Logs**
https://gist.github.com/janagyjr/8d2ba0b1a8d6777a9d68125ea88e5b1d

**Comment by NielsPilgaard** [comment]
Please try with JRE or JDK instead of OpenJDK.

**Comment by janagyjr** [comment]
Is there anyway to get it working with OpenJDK? I have other Minecraft servers running that use OpenJDK.

**Comment by NielsPilgaard** [comment]
I'm afraid I don't know. Fixing the malformed JSON errors would probably fix it, but there are thousands.

**Comment by janagyjr** [comment]
Then rip server for my community.

**Comment by janagyjr** [comment]
Also, fwiw, even a community gaming server is not 'personal use', which is why a lot of repo's for oracle java are dead. OpenJDK is the only legal alternative.

**Comment by NielsPilgaard** [comment]
Don't worry, I'm working on reporting bugs, we'll get the malformed JSON bugs squashed eventually, it just takes time.

**Comment by janagyjr** [comment]
I'm not worried, just a tad disappointed tbh. Not your fault. We'll chill with some other pack for now.

**Comment by NielsPilgaard** [comment]
Note to self: This needs to be seperated into smaller issues.
