### ISSUE TITLE
Server Hanging

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica4#55]
Enigmatica 4 current has a bug where the server becomes unresponsive, and then kicks all players. Once everyone is kicked, it'll show the players as still on. The server doesn't respond to console input at this time.

There are no clues as to the cause in the server logs, but this is printed in the client logs:

```
[13:05:32] [Client thread/ERROR]: ########## GL ERROR ##########
[13:05:32] [Client thread/ERROR]: @ Render
[13:05:32] [Client thread/ERROR]: 65539: Invalid key 0
[13:05:51] [Client thread/ERROR]: ########## GL ERROR ##########
[13:05:51] [Client thread/ERROR]: @ Render
[13:05:51] [Client thread/ERROR]: 65539: Invalid key 0
[13:06:06] [Client thread/INFO]: Loaded 44 advancements
[13:06:31] [Client thread/ERROR]: ########## GL ERROR ##########
[13:06:31] [Client thread/ERROR]: @ Render
[13:06:31] [Client thread/ERROR]: 65539: Invalid key 0
[13:06:43] [Client thread/WARN]: World unload
```

That is the last message.
If anyone has any ideas what could be causing this, please let me know.

**Comment by NillerMedDild** [comment]
https://gist.github.com/NillerMedDild/c088f6647d540061116cbd3900fcb9d3

**Comment by NielsPilgaard** [comment]
https://gist.github.com/NillerMedDild/c088f6647d540061116cbd3900fcb9d3

<blockquote><img src="https://github.githubassets.com/images/modules/gists/gist-og-image.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/NillerMedDild/c088f6647d540061116cbd3900fcb9d3">ClearedMods.txt</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by NielsPilgaard** [comment]
We've managed to make it occur far less often by removing Zombie Horse Spawn, Skeleton Horse Spawn, Zombie Villagers From Spawners and Villager Names, but it does still happen. We believe it is tied to the forge I/O TPS issue.

**Comment by ArbitraryHubris** [comment]
Have you seen this cpw thread?  https://twitter.com/voxcpw/status/1184948750587957248

Seems likely to be related to our hanging server issues.

<blockquote><img src="https://pbs.twimg.com/profile_images/1087181295770308609/gS8hSZ-Z_400x400.jpg" width="48" align="right"><div>Twitter</div><div><strong><a href="https://twitter.com/voxcpw/status/1184948750587957248">cpw on Twitter</a></strong></div><div>“Some stuff on tps and 1.14. apparently there was a fairly important change to how the server saves to disk in 1.14 (technically 1.13, but who's counting?)

From around 1.8 or so, there's been what's known as a writebehind thread - basically a thread dedicated to writing...”</div></blockquote>

**Comment by NielsPilgaard** [comment]
Yes that is the I/O TPS issue I refer to :)

**Comment by ArbitraryHubris** [comment]
I figured!  Just making sure!
