### ISSUE TITLE
Add Nomadic Tents(!)

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica4#6]
https://www.curseforge.com/minecraft/mc-mods/nomadic-tents

**Comment by Frikkle** [comment]
Awesome, do want.

**Comment by NielsPilgaard** [comment]
IKR! It just needs some bug fixes first.

**Comment by NielsPilgaard** [comment]
It doesn't look like the bug fixes will ever be made.
