### ISSUE TITLE
Unable to install on Twitch Launcher

### ISSUE THREAD

**Issue by Tkdriverx** [NillerMedDild/Enigmatica4#99]
v 0.1.5+ will not install, receives this error:
![image](https://user-images.githubusercontent.com/9004164/67642066-77ed9d80-f8de-11e9-911d-c55a33b01449.png)

**Comment by NielsPilgaard** [comment]
Couldn't try downloading the file from the website and import it please?

**Comment by Tkdriverx** [comment]
I get the same error when attempting to import.

It might be a specific mod that doesn't exist on the curse servers anymore? But for some reason Twitch doesn't give enough information. This is only one of two packs that I have this issue with. (The other is FTB Unstable 1.14)

I've done some looking into it, and discovered it's the Forge version that you're using. It's available in the "create custom profile" dropdown, but it will fail to find the file.

**Comment by NielsPilgaard** [comment]
That Forge version is available though, not everyone has this problem. It's a Twitch issue. Try the GDLauncher :)

**Comment by Tkdriverx** [comment]
I have never heard of that launcher, but it does install on GDLauncher.

That is strange that it's not happening to everyone...

**Comment by NielsPilgaard** [comment]
That's Twitch for ya' :P
